FROM genuin-webapp-build as build

FROM node:14-slim

WORKDIR /genuin-webapp-prod

COPY  --from=build /genuin-webapp/package*.json ./
COPY  --from=build /genuin-webapp/.next ./.next
COPY  --from=build /genuin-webapp/node_modules ./node_modules
COPY  --from=build /genuin-webapp/public ./public

EXPOSE 4000

CMD [ "npm", "start" ]