version: '3.8'

services:
  genuin-webapp-production:
    image: genuin-webapp-$environment:latest
    build: 
      context: .
      dockerfile: Dockerfile.production
    ports:
      - 4000:4000
    env_file:
      - ./.env.production
      - ./.env.production.local