FROM node:14 AS build

WORKDIR /genuin-webapp
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:14 

WORKDIR /genuin-webapp-prod

COPY --from=build /genuin-webapp/package*.json ./
COPY --from=build /genuin-webapp/.next ./.next
COPY --from=build /genuin-webapp/node_modules ./node_modules

EXPOSE 4000

CMD [ "npm", "start" ]