import type { InfiniteData } from "@tanstack/react-query";

import type { FeedPage } from "@genuin/components/react-query/api/feed";

// Example fake feedData for Storybook
export const testFeedData: InfiniteData<FeedPage> = {
  pages: [
    {
      feed: [
        {
          video: {
            id: "d3462334-f4d1-497c-ae53-33c313485b4a",
            type: "video",
            createdAt: 1755172498000,
            commentCount: 39,
            shareUrl:
              "https://tsilrac.qa.begenuin.com/video/honda-city-honda-city-sedan-ehev-rs-yourcar?community=1fa079ce3e000d64&loop=1fdbea0285001400",
            attachedLink: null,
            source: "https://vz-eee5e913-a30.b-cdn.net/0141acec-43c4-4247-9ff9-3938325aeae7/playlist.m3u8",
            isSparked: false,
            isWatched: false,
            sparkCount: 22,
            thumbnail: "https://vz-eee5e913-a30.b-cdn.net/0141acec-43c4-4247-9ff9-3938325aeae7/thumbnail.jpg",
            viewCount: 34,
            thumbnailM: null,
            description: ["Honda City - Honda City Sedan e:HEV RS #yourcar"],
            descritptionText: "Honda City - Honda City Sedan e:HEV RS #yourcar",
            slug: "honda-city-honda-city-sedan-ehev-rs-yourcar",
            linkoutId: 4046,
            clickableUrl: null,
            linkouts: [
              {
                cta_link: "https://carlist.my/",
                cta_text: "Find Your New Car",
                links: [
                  {
                    image: "https://media.qa.begenuin.com/uploads/linkouts/linkouts_1771428351123.png",
                    link: "https://hondacarindia.com/",
                    position: 1,
                    title: "Honda India | Check Out Honda's Newest Sedans and SUVs",
                  },
                ],
                style: 1,
              },
            ],
            isPinned: false,
            thumbnailSprite: "https://media.qa.begenuin.com/uploads/sprite/689dcb6f5eea23f81fbbe7da_1755172497568.jpeg",
            cardLayoutId: 1,
            videoLayoutId: 1,
            duration: 58,
            attributes: null,
            placement_card_layout_id: null,
            placement_video_layout_id: null,
            placement_card_section_layout_id: null,
          },
          group: {
            id: "1184c364-ab08-44a3-87bb-e02cdae6256b",
            slug: "new-launch-watch",
            description: "Stay ahead with previews of new models, sneak peeks from auto shows, and feature breakdowns.",
            shareUrl: "https://tsilrac.qa.begenuin.com/loop/new-launch-watch?community=1fa079ce3e000d64",
            name: "New Launch Watch",
            isSubscribed: false,
            role: "UNJOINED",
            isPrivate: false,
          },
          community: {
            id: "18195045-22cb-49d3-b466-6d71dd995e05",
            shareUrl: "https://tsilrac.qa.begenuin.com/community/car-gurus-malaysia",
            slug: "car-gurus-malaysia",
            handle: "cargurusmalaysia",
            isPrivate: false,
            userRole: "UNJOINED",
            type: 1,
            name: "🚗 Car Gurus Malaysia",
            profileImage: null,
            membersCount: 8,
            groupsCount: 5,
            postsCount: 49,
            brand: {
              id: 3075,
              name: "Carlist",
              slug: "carlist-vu9m",
              webLogo: "https://media.qa.begenuin.com/uploads/brands/web_logo/Carlist_weblogo_1748946784.png",
              userLogo: 2,
              handle: "Carlistmy",
            },
          },
          owner: {
            profileImage: "https://media.qa.begenuin.com/uploads/profile_images/s/brandProfileLogo_1748947686562.png",
            isAvatar: false,
            userName: "Carlistmy",
            name: "Carlist",
            bio: null,
            shareUrl: "https://tsilrac.qa.begenuin.com/profile/Carlistmy",
            brand: {
              id: 3075,
              slug: "carlist-vu9m",
              userLogo: 2,
            },
          },
          section: {
            id: null,
            title: null,
            description: null,
            position: null,
            thumbnail_url: null,
            cover_url: null,
            no_of_clips: null,
          },
        },
        {
          video: {
            id: "42765099-cbf3-4b4c-a04b-70e89e643b89",
            type: "video",
            createdAt: 1755172433000,
            commentCount: 22,
            shareUrl:
              "https://tsilrac.qa.begenuin.com/video/discover-the-incredible-2015-honda-city-15-v?community=1fa079ce3e000d64&loop=1fa07a0c2e001404",
            attachedLink: null,
            source: "https://vz-eee5e913-a30.b-cdn.net/66005c38-4691-4b7c-be15-dc24544c145d/playlist.m3u8",
            isSparked: false,
            isWatched: false,
            sparkCount: 10,
            thumbnail: "https://vz-eee5e913-a30.b-cdn.net/66005c38-4691-4b7c-be15-dc24544c145d/thumbnail.jpg",
            viewCount: 1,
            thumbnailM: null,
            description: [
              "Discover the incredible 2015 Honda City 1.5 V, priced at just RM44,800! Enjoy a premium experience with low mileage, a powerful engine, and exciting features. Don’t miss out on this unbeatable car deal—click now for details that could transform your ride!",
            ],
            descritptionText:
              "Discover the incredible 2015 Honda City 1.5 V, priced at just RM44,800! Enjoy a premium experience with low mileage, a powerful engine, and exciting features. Don’t miss out on this unbeatable car deal—click now for details that could transform your ride!",
            slug: "discover-the-incredible-2015-honda-city-15-v",
            linkoutId: null,
            clickableUrl: null,
            linkouts: [],
            isPinned: false,
            thumbnailSprite: "https://media.qa.begenuin.com/uploads/sprite/689dcb4739a3a8caa4568c2b_1755172432883.jpeg",
            cardLayoutId: 1,
            videoLayoutId: 1,
            duration: 49,
            attributes: null,
            placement_card_layout_id: null,
            placement_video_layout_id: null,
            placement_card_section_layout_id: null,
          },
          group: {
            id: "65f0a6aa-983b-4971-9849-ae45df2dc49b",
            slug: "smart-car-deals",
            description: "Best value buys, trade-in tricks & resale hacks for Malaysian car buyers",
            shareUrl: "https://tsilrac.qa.begenuin.com/loop/smart-car-deals?community=1fa079ce3e000d64",
            name: "💸 Smart Car Deals",
            isSubscribed: false,
            role: "UNJOINED",
            isPrivate: false,
          },
          community: {
            id: "18195045-22cb-49d3-b466-6d71dd995e05",
            shareUrl: "https://tsilrac.qa.begenuin.com/community/car-gurus-malaysia",
            slug: "car-gurus-malaysia",
            handle: "cargurusmalaysia",
            isPrivate: false,
            userRole: "UNJOINED",
            type: 1,
            name: "🚗 Car Gurus Malaysia",
            profileImage: null,
            membersCount: 8,
            groupsCount: 5,
            postsCount: 49,
            brand: {
              id: 3075,
              name: "Carlist",
              slug: "carlist-vu9m",
              webLogo: "https://media.qa.begenuin.com/uploads/brands/web_logo/Carlist_weblogo_1748946784.png",
              userLogo: 2,
              handle: "Carlistmy",
            },
          },
          owner: {
            profileImage: "https://media.qa.begenuin.com/uploads/profile_images/s/brandProfileLogo_1748947686562.png",
            isAvatar: false,
            userName: "Carlistmy",
            name: "Carlist",
            bio: null,
            shareUrl: "https://tsilrac.qa.begenuin.com/profile/Carlistmy",
            brand: {
              id: 3075,
              slug: "carlist-vu9m",
              userLogo: 2,
            },
          },
          section: {
            id: null,
            title: null,
            description: null,
            position: null,
            thumbnail_url: null,
            cover_url: null,
            no_of_clips: null,
          },
        },
        {
          video: {
            id: "aaed7a37-4a2f-4955-a2d3-fad873251a28",
            type: "video",
            createdAt: 1755172416000,
            commentCount: 10,
            shareUrl:
              "https://tsilrac.qa.begenuin.com/video/discover-the-honda-en-1-malaysias-first-dedicated?community=1fa079ce3e000d64&loop=1fa07a0c2e001404",
            attachedLink: null,
            source: "https://vz-eee5e913-a30.b-cdn.net/63d1c2e2-40ac-4f79-9b07-0391a10b74f6/playlist.m3u8",
            isSparked: false,
            isWatched: false,
            sparkCount: 9,
            thumbnail: "https://vz-eee5e913-a30.b-cdn.net/63d1c2e2-40ac-4f79-9b07-0391a10b74f6/thumbnail.jpg",
            viewCount: 0,
            thumbnailM: null,
            description: [
              "Discover the Honda EN1, Malaysia's first dedicated EV! Priced under $150,000 ringgit, this innovative vehicle boasts impressive specs and design insights. Delve into its unique features compared to the HRV and join the discussion on whether it's worth the investment.",
            ],
            descritptionText:
              "Discover the Honda EN1, Malaysia's first dedicated EV! Priced under $150,000 ringgit, this innovative vehicle boasts impressive specs and design insights. Delve into its unique features compared to the HRV and join the discussion on whether it's worth the investment.",
            slug: "discover-the-honda-en-1-malaysias-first-dedicated",
            linkoutId: null,
            clickableUrl: null,
            linkouts: [],
            isPinned: false,
            thumbnailSprite: "https://media.qa.begenuin.com/uploads/sprite/689dcb1f55816c444b4e7df3_1755172415733.jpeg",
            cardLayoutId: 1,
            videoLayoutId: 1,
            duration: 109,
            attributes: null,
            placement_card_layout_id: null,
            placement_video_layout_id: null,
            placement_card_section_layout_id: null,
          },
          group: {
            id: "65f0a6aa-983b-4971-9849-ae45df2dc49b",
            slug: "smart-car-deals",
            description: "Best value buys, trade-in tricks & resale hacks for Malaysian car buyers",
            shareUrl: "https://tsilrac.qa.begenuin.com/loop/smart-car-deals?community=1fa079ce3e000d64",
            name: "💸 Smart Car Deals",
            isSubscribed: false,
            role: "UNJOINED",
            isPrivate: false,
          },
          community: {
            id: "18195045-22cb-49d3-b466-6d71dd995e05",
            shareUrl: "https://tsilrac.qa.begenuin.com/community/car-gurus-malaysia",
            slug: "car-gurus-malaysia",
            handle: "cargurusmalaysia",
            isPrivate: false,
            userRole: "UNJOINED",
            type: 1,
            name: "🚗 Car Gurus Malaysia",
            profileImage: null,
            membersCount: 8,
            groupsCount: 5,
            postsCount: 49,
            brand: {
              id: 3075,
              name: "Carlist",
              slug: "carlist-vu9m",
              webLogo: "https://media.qa.begenuin.com/uploads/brands/web_logo/Carlist_weblogo_1748946784.png",
              userLogo: 2,
              handle: "Carlistmy",
            },
          },
          owner: {
            profileImage: "https://media.qa.begenuin.com/uploads/profile_images/s/brandProfileLogo_1748947686562.png",
            isAvatar: false,
            userName: "Carlistmy",
            name: "Carlist",
            bio: null,
            shareUrl: "https://tsilrac.qa.begenuin.com/profile/Carlistmy",
            brand: {
              id: 3075,
              slug: "carlist-vu9m",
              userLogo: 2,
            },
          },
          section: {
            id: null,
            title: null,
            description: null,
            position: null,
            thumbnail_url: null,
            cover_url: null,
            no_of_clips: null,
          },
        },
        {
          video: {
            id: "b197bf77-335d-45f2-89f2-f220303ca5a5",
            type: "video",
            createdAt: 1751540945000,
            commentCount: 22,
            shareUrl:
              "https://tsilrac.qa.begenuin.com/video/1fedc7ae1e001416?community=1fa079ce3e000d64&loop=1fdbeab83d801402",
            attachedLink: null,
            source: "https://vz-eee5e913-a30.b-cdn.net/45977b2e-21a9-48ee-9fd0-5488b8d88801/playlist.m3u8",
            isSparked: false,
            isWatched: false,
            sparkCount: 10,
            thumbnail: "https://vz-eee5e913-a30.b-cdn.net/45977b2e-21a9-48ee-9fd0-5488b8d88801/thumbnail.jpg",
            viewCount: 0,
            thumbnailM: null,
            description: null,
            descritptionText: null,
            slug: "1fedc7ae1e001416",
            linkoutId: null,
            clickableUrl: null,
            linkouts: [],
            isPinned: false,
            thumbnailSprite: null,
            cardLayoutId: 1,
            videoLayoutId: 1,
            duration: 8,
            attributes: null,
            placement_card_layout_id: null,
            placement_video_layout_id: null,
            placement_card_section_layout_id: null,
          },
          group: {
            id: "20da9771-cbef-4be7-87cb-11739d4bed29",
            slug: "car-care-gurus",
            description:
              "Keep it mint! Tips on detailing, DIY maintenance, and the best products for interior & exterior care.",
            shareUrl: "https://tsilrac.qa.begenuin.com/loop/car-care-gurus?community=1fa079ce3e000d64",
            name: "Car Care Gurus",
            isSubscribed: false,
            role: "UNJOINED",
            isPrivate: false,
          },
          community: {
            id: "18195045-22cb-49d3-b466-6d71dd995e05",
            shareUrl: "https://tsilrac.qa.begenuin.com/community/car-gurus-malaysia",
            slug: "car-gurus-malaysia",
            handle: "cargurusmalaysia",
            isPrivate: false,
            userRole: "UNJOINED",
            type: 1,
            name: "🚗 Car Gurus Malaysia",
            profileImage: null,
            membersCount: 8,
            groupsCount: 5,
            postsCount: 49,
            brand: {
              id: 3075,
              name: "Carlist",
              slug: "carlist-vu9m",
              webLogo: "https://media.qa.begenuin.com/uploads/brands/web_logo/Carlist_weblogo_1748946784.png",
              userLogo: 2,
              handle: "Carlistmy",
            },
          },
          owner: {
            profileImage: "smiling_face_with_sunglasses",
            isAvatar: true,
            userName: "tedyy",
            name: "fghjv",
            bio: "gfjb",
            shareUrl: "https://tsilrac.qa.begenuin.com/profile/tedyy",
            brand: null,
          },
          section: {
            id: null,
            title: null,
            description: null,
            position: null,
            thumbnail_url: null,
            cover_url: null,
            no_of_clips: null,
          },
        },
        {
          video: {
            id: "954147b3-d406-4885-b519-642a57af950d",
            type: "video",
            createdAt: 1751540840000,
            commentCount: 7,
            shareUrl:
              "https://tsilrac.qa.begenuin.com/video/1fedc6e17e801414?community=1fa079ce3e000d64&loop=1fdbeab83d801402",
            attachedLink: null,
            source: "https://vz-eee5e913-a30.b-cdn.net/90509d4f-5202-40c9-bdc5-9b209e4523aa/playlist.m3u8",
            isSparked: false,
            isWatched: false,
            sparkCount: 6,
            thumbnail: "https://vz-eee5e913-a30.b-cdn.net/90509d4f-5202-40c9-bdc5-9b209e4523aa/thumbnail.jpg",
            viewCount: 0,
            thumbnailM: null,
            description: null,
            descritptionText: null,
            slug: "1fedc6e17e801414",
            linkoutId: null,
            clickableUrl: null,
            linkouts: [],
            isPinned: false,
            thumbnailSprite: null,
            cardLayoutId: 1,
            videoLayoutId: 1,
            duration: 7,
            attributes: null,
            placement_card_layout_id: null,
            placement_video_layout_id: null,
            placement_card_section_layout_id: null,
          },
          group: {
            id: "20da9771-cbef-4be7-87cb-11739d4bed29",
            slug: "car-care-gurus",
            description:
              "Keep it mint! Tips on detailing, DIY maintenance, and the best products for interior & exterior care.",
            shareUrl: "https://tsilrac.qa.begenuin.com/loop/car-care-gurus?community=1fa079ce3e000d64",
            name: "Car Care Gurus",
            isSubscribed: false,
            role: "UNJOINED",
            isPrivate: false,
          },
          community: {
            id: "18195045-22cb-49d3-b466-6d71dd995e05",
            shareUrl: "https://tsilrac.qa.begenuin.com/community/car-gurus-malaysia",
            slug: "car-gurus-malaysia",
            handle: "cargurusmalaysia",
            isPrivate: false,
            userRole: "UNJOINED",
            type: 1,
            name: "🚗 Car Gurus Malaysia",
            profileImage: null,
            membersCount: 8,
            groupsCount: 5,
            postsCount: 49,
            brand: {
              id: 3075,
              name: "Carlist",
              slug: "carlist-vu9m",
              webLogo: "https://media.qa.begenuin.com/uploads/brands/web_logo/Carlist_weblogo_1748946784.png",
              userLogo: 2,
              handle: "Carlistmy",
            },
          },
          owner: {
            profileImage: "smiling_face_with_sunglasses",
            isAvatar: true,
            userName: "tedyy",
            name: "fghjv",
            bio: "gfjb",
            shareUrl: "https://tsilrac.qa.begenuin.com/profile/tedyy",
            brand: null,
          },
          section: {
            id: null,
            title: null,
            description: null,
            position: null,
            thumbnail_url: null,
            cover_url: null,
            no_of_clips: null,
          },
        },
        {
          video: {
            id: "158f7dcf-d8f4-48bf-8da7-6de74f8945b2",
            type: "video",
            createdAt: 1750941871000,
            commentCount: 3,
            shareUrl:
              "https://tsilrac.qa.begenuin.com/video/follow-us-website-httpswwwcarlistmy-facebook-1e7t?community=1fa079ce3e000d64&loop=1fdbeab83d801402",
            attachedLink: null,
            source: "https://vz-eee5e913-a30.b-cdn.net/4d001dae-4b58-498e-a48d-ab8a401ad482/playlist.m3u8",
            isSparked: false,
            isWatched: false,
            sparkCount: 2,
            thumbnail: "https://vz-eee5e913-a30.b-cdn.net/4d001dae-4b58-498e-a48d-ab8a401ad482/thumbnail.jpg",
            viewCount: 0,
            thumbnailM: null,
            description: [
              "Follow us:\nWebsite: https://www.carlist.my\nFacebook: https://www.facebook.com/Carlist.my\nInstagram: https://www.instagram.com/carlistmy\nTiktok: https://www.tiktok.com/@carlistmy\nCarTell: https://www.facebook.com/groups/cartell",
            ],
            descritptionText:
              "Follow us:\nWebsite: https://www.carlist.my\nFacebook: https://www.facebook.com/Carlist.my\nInstagram: https://www.instagram.com/carlistmy\nTiktok: https://www.tiktok.com/@carlistmy\nCarTell: https://www.facebook.com/groups/cartell",
            slug: "follow-us-website-httpswwwcarlistmy-facebook-1e7t",
            linkoutId: null,
            clickableUrl: null,
            linkouts: [],
            isPinned: false,
            thumbnailSprite: null,
            cardLayoutId: 1,
            videoLayoutId: 1,
            duration: 114,
            attributes: null,
            placement_card_layout_id: null,
            placement_video_layout_id: null,
            placement_card_section_layout_id: null,
          },
          group: {
            id: "20da9771-cbef-4be7-87cb-11739d4bed29",
            slug: "car-care-gurus",
            description:
              "Keep it mint! Tips on detailing, DIY maintenance, and the best products for interior & exterior care.",
            shareUrl: "https://tsilrac.qa.begenuin.com/loop/car-care-gurus?community=1fa079ce3e000d64",
            name: "Car Care Gurus",
            isSubscribed: false,
            role: "UNJOINED",
            isPrivate: false,
          },
          community: {
            id: "18195045-22cb-49d3-b466-6d71dd995e05",
            shareUrl: "https://tsilrac.qa.begenuin.com/community/car-gurus-malaysia",
            slug: "car-gurus-malaysia",
            handle: "cargurusmalaysia",
            isPrivate: false,
            userRole: "UNJOINED",
            type: 1,
            name: "🚗 Car Gurus Malaysia",
            profileImage: null,
            membersCount: 8,
            groupsCount: 5,
            postsCount: 49,
            brand: {
              id: 3075,
              name: "Carlist",
              slug: "carlist-vu9m",
              webLogo: "https://media.qa.begenuin.com/uploads/brands/web_logo/Carlist_weblogo_1748946784.png",
              userLogo: 2,
              handle: "Carlistmy",
            },
          },
          owner: {
            profileImage: "https://media.qa.begenuin.com/uploads/profile_images/s/brandProfileLogo_1748947686562.png",
            isAvatar: false,
            userName: "Carlistmy",
            name: "Carlist",
            bio: null,
            shareUrl: "https://tsilrac.qa.begenuin.com/profile/Carlistmy",
            brand: {
              id: 3075,
              slug: "carlist-vu9m",
              userLogo: 2,
            },
          },
          section: {
            id: null,
            title: null,
            description: null,
            position: null,
            thumbnail_url: null,
            cover_url: null,
            no_of_clips: null,
          },
        },
        {
          video: {
            id: "c32dac0d-a1b2-4879-ad6b-4aea6bdba72e",
            type: "video",
            createdAt: 1750941870000,
            commentCount: 3,
            shareUrl:
              "https://tsilrac.qa.begenuin.com/video/follow-us-website-httpswwwcarlistmy-facebook-17be?community=1fa079ce3e000d64&loop=1fdbeab83d801402",
            attachedLink: null,
            source: "https://vz-eee5e913-a30.b-cdn.net/350b4871-6ebf-490a-94c0-77390b38f58e/playlist.m3u8",
            isSparked: false,
            isWatched: false,
            sparkCount: 9,
            thumbnail: "https://vz-eee5e913-a30.b-cdn.net/350b4871-6ebf-490a-94c0-77390b38f58e/thumbnail.jpg",
            viewCount: 0,
            thumbnailM: null,
            description: [
              "Follow us:\nWebsite: https://www.carlist.my\nFacebook: https://www.facebook.com/Carlist.my\nInstagram: https://www.instagram.com/carlistmy\nTiktok: https://www.tiktok.com/@carlistmy\nCarTell: https://www.facebook.com/groups/cartell\n\n\n#Toyota #ToyotaAlphard #Alphard #AGH30 #MPV #Carlist #UsedCars",
            ],
            descritptionText:
              "Follow us:\nWebsite: https://www.carlist.my\nFacebook: https://www.facebook.com/Carlist.my\nInstagram: https://www.instagram.com/carlistmy\nTiktok: https://www.tiktok.com/@carlistmy\nCarTell: https://www.facebook.com/groups/cartell\n\n\n#Toyota #ToyotaAlphard #Alphard #AGH30 #MPV #Carlist #UsedCars",
            slug: "follow-us-website-httpswwwcarlistmy-facebook-17be",
            linkoutId: null,
            clickableUrl: null,
            linkouts: [],
            isPinned: false,
            thumbnailSprite: null,
            cardLayoutId: 1,
            videoLayoutId: 1,
            duration: 56,
            attributes: null,
            placement_card_layout_id: null,
            placement_video_layout_id: null,
            placement_card_section_layout_id: null,
          },
          group: {
            id: "20da9771-cbef-4be7-87cb-11739d4bed29",
            slug: "car-care-gurus",
            description:
              "Keep it mint! Tips on detailing, DIY maintenance, and the best products for interior & exterior care.",
            shareUrl: "https://tsilrac.qa.begenuin.com/loop/car-care-gurus?community=1fa079ce3e000d64",
            name: "Car Care Gurus",
            isSubscribed: false,
            role: "UNJOINED",
            isPrivate: false,
          },
          community: {
            id: "18195045-22cb-49d3-b466-6d71dd995e05",
            shareUrl: "https://tsilrac.qa.begenuin.com/community/car-gurus-malaysia",
            slug: "car-gurus-malaysia",
            handle: "cargurusmalaysia",
            isPrivate: false,
            userRole: "UNJOINED",
            type: 1,
            name: "🚗 Car Gurus Malaysia",
            profileImage: null,
            membersCount: 8,
            groupsCount: 5,
            postsCount: 49,
            brand: {
              id: 3075,
              name: "Carlist",
              slug: "carlist-vu9m",
              webLogo: "https://media.qa.begenuin.com/uploads/brands/web_logo/Carlist_weblogo_1748946784.png",
              userLogo: 2,
              handle: "Carlistmy",
            },
          },
          owner: {
            profileImage: "https://media.qa.begenuin.com/uploads/profile_images/s/brandProfileLogo_1748947686562.png",
            isAvatar: false,
            userName: "Carlistmy",
            name: "Carlist",
            bio: null,
            shareUrl: "https://tsilrac.qa.begenuin.com/profile/Carlistmy",
            brand: {
              id: 3075,
              slug: "carlist-vu9m",
              userLogo: 2,
            },
          },
          section: {
            id: null,
            title: null,
            description: null,
            position: null,
            thumbnail_url: null,
            cover_url: null,
            no_of_clips: null,
          },
        },
        {
          video: {
            id: "5e20e695-5e0a-4c00-9b61-0045bbe27069",
            type: "video",
            createdAt: 1750941870000,
            commentCount: 1,
            shareUrl:
              "https://tsilrac.qa.begenuin.com/video/follow-us-website-httpswwwcarlistmy-facebook-hd0j?community=1fa079ce3e000d64&loop=1fdbeab83d801402",
            attachedLink: null,
            source: "https://vz-eee5e913-a30.b-cdn.net/c901d6d0-9dcf-437e-9743-e7c18b54e804/playlist.m3u8",
            isSparked: false,
            isWatched: false,
            sparkCount: 2,
            thumbnail: "https://vz-eee5e913-a30.b-cdn.net/c901d6d0-9dcf-437e-9743-e7c18b54e804/thumbnail.jpg",
            viewCount: 1,
            thumbnailM: null,
            description: [
              "Follow us:\nWebsite: https://www.carlist.my\nFacebook: https://www.facebook.com/Carlist.my\nInstagram: https://www.instagram.com/carlistmy\nTiktok: https://www.tiktok.com/@carlistmy\nCarTell: https://www.facebook.com/groups/cartell\n\n#Volvo #VolvoV40 #VolvoV40CrossCountry #V40 #T5 #CrossCountry #Carlist #UsedCars",
            ],
            descritptionText:
              "Follow us:\nWebsite: https://www.carlist.my\nFacebook: https://www.facebook.com/Carlist.my\nInstagram: https://www.instagram.com/carlistmy\nTiktok: https://www.tiktok.com/@carlistmy\nCarTell: https://www.facebook.com/groups/cartell\n\n#Volvo #VolvoV40 #VolvoV40CrossCountry #V40 #T5 #CrossCountry #Carlist #UsedCars",
            slug: "follow-us-website-httpswwwcarlistmy-facebook-hd0j",
            linkoutId: null,
            clickableUrl: null,
            linkouts: [],
            isPinned: false,
            thumbnailSprite: null,
            cardLayoutId: 1,
            videoLayoutId: 1,
            duration: 53,
            attributes: null,
            placement_card_layout_id: null,
            placement_video_layout_id: null,
            placement_card_section_layout_id: null,
          },
          group: {
            id: "20da9771-cbef-4be7-87cb-11739d4bed29",
            slug: "car-care-gurus",
            description:
              "Keep it mint! Tips on detailing, DIY maintenance, and the best products for interior & exterior care.",
            shareUrl: "https://tsilrac.qa.begenuin.com/loop/car-care-gurus?community=1fa079ce3e000d64",
            name: "Car Care Gurus",
            isSubscribed: false,
            role: "UNJOINED",
            isPrivate: false,
          },
          community: {
            id: "18195045-22cb-49d3-b466-6d71dd995e05",
            shareUrl: "https://tsilrac.qa.begenuin.com/community/car-gurus-malaysia",
            slug: "car-gurus-malaysia",
            handle: "cargurusmalaysia",
            isPrivate: false,
            userRole: "UNJOINED",
            type: 1,
            name: "🚗 Car Gurus Malaysia",
            profileImage: null,
            membersCount: 8,
            groupsCount: 5,
            postsCount: 49,
            brand: {
              id: 3075,
              name: "Carlist",
              slug: "carlist-vu9m",
              webLogo: "https://media.qa.begenuin.com/uploads/brands/web_logo/Carlist_weblogo_1748946784.png",
              userLogo: 2,
              handle: "Carlistmy",
            },
          },
          owner: {
            profileImage: "https://media.qa.begenuin.com/uploads/profile_images/s/brandProfileLogo_1748947686562.png",
            isAvatar: false,
            userName: "Carlistmy",
            name: "Carlist",
            bio: null,
            shareUrl: "https://tsilrac.qa.begenuin.com/profile/Carlistmy",
            brand: {
              id: 3075,
              slug: "carlist-vu9m",
              userLogo: 2,
            },
          },
          section: {
            id: null,
            title: null,
            description: null,
            position: null,
            thumbnail_url: null,
            cover_url: null,
            no_of_clips: null,
          },
        },
        {
          video: {
            id: "4b390e83-8490-4738-b679-4493a8c95cf0",
            type: "video",
            createdAt: 1750941861000,
            commentCount: 2,
            shareUrl:
              "https://tsilrac.qa.begenuin.com/video/follow-us-website-httpswwwcarlistmy-facebook-dx3d?community=1fa079ce3e000d64&loop=1fdbeab83d801402",
            attachedLink: null,
            source: "https://vz-eee5e913-a30.b-cdn.net/18f2c0ab-720f-4e68-b02f-ade10948e05e/playlist.m3u8",
            isSparked: false,
            isWatched: false,
            sparkCount: 3,
            thumbnail: "https://vz-eee5e913-a30.b-cdn.net/18f2c0ab-720f-4e68-b02f-ade10948e05e/thumbnail.jpg",
            viewCount: 1,
            thumbnailM: null,
            description: [
              "Follow us:\nWebsite: https://www.carlist.my\nFacebook: https://www.facebook.com/Carlist.my\nInstagram: https://www.instagram.com/carlistmy\nTiktok: https://www.tiktok.com/@carlistmy\nCarTell: https://www.facebook.com/groups/cartell",
            ],
            descritptionText:
              "Follow us:\nWebsite: https://www.carlist.my\nFacebook: https://www.facebook.com/Carlist.my\nInstagram: https://www.instagram.com/carlistmy\nTiktok: https://www.tiktok.com/@carlistmy\nCarTell: https://www.facebook.com/groups/cartell",
            slug: "follow-us-website-httpswwwcarlistmy-facebook-dx3d",
            linkoutId: null,
            clickableUrl: null,
            linkouts: [],
            isPinned: false,
            thumbnailSprite: null,
            cardLayoutId: 1,
            videoLayoutId: 1,
            duration: 44,
            attributes: null,
            placement_card_layout_id: null,
            placement_video_layout_id: null,
            placement_card_section_layout_id: null,
          },
          group: {
            id: "20da9771-cbef-4be7-87cb-11739d4bed29",
            slug: "car-care-gurus",
            description:
              "Keep it mint! Tips on detailing, DIY maintenance, and the best products for interior & exterior care.",
            shareUrl: "https://tsilrac.qa.begenuin.com/loop/car-care-gurus?community=1fa079ce3e000d64",
            name: "Car Care Gurus",
            isSubscribed: false,
            role: "UNJOINED",
            isPrivate: false,
          },
          community: {
            id: "18195045-22cb-49d3-b466-6d71dd995e05",
            shareUrl: "https://tsilrac.qa.begenuin.com/community/car-gurus-malaysia",
            slug: "car-gurus-malaysia",
            handle: "cargurusmalaysia",
            isPrivate: false,
            userRole: "UNJOINED",
            type: 1,
            name: "🚗 Car Gurus Malaysia",
            profileImage: null,
            membersCount: 8,
            groupsCount: 5,
            postsCount: 49,
            brand: {
              id: 3075,
              name: "Carlist",
              slug: "carlist-vu9m",
              webLogo: "https://media.qa.begenuin.com/uploads/brands/web_logo/Carlist_weblogo_1748946784.png",
              userLogo: 2,
              handle: "Carlistmy",
            },
          },
          owner: {
            profileImage: "https://media.qa.begenuin.com/uploads/profile_images/s/brandProfileLogo_1748947686562.png",
            isAvatar: false,
            userName: "Carlistmy",
            name: "Carlist",
            bio: null,
            shareUrl: "https://tsilrac.qa.begenuin.com/profile/Carlistmy",
            brand: {
              id: 3075,
              slug: "carlist-vu9m",
              userLogo: 2,
            },
          },
          section: {
            id: null,
            title: null,
            description: null,
            position: null,
            thumbnail_url: null,
            cover_url: null,
            no_of_clips: null,
          },
        },
        {
          video: {
            id: "2fcf3ce5-9fcf-43ba-a62c-2e7ed6d5a900",
            type: "video",
            createdAt: 1750941860000,
            commentCount: 6,
            shareUrl:
              "https://tsilrac.qa.begenuin.com/video/follow-us-website-httpswwwcarlistmy-facebook-fe03?community=1fa079ce3e000d64&loop=1fdbeab83d801402",
            attachedLink: null,
            source: "https://vz-eee5e913-a30.b-cdn.net/3d246838-2ef4-4487-9ef7-061d57f6dc98/playlist.m3u8",
            isSparked: false,
            isWatched: false,
            sparkCount: 5,
            thumbnail: "https://vz-eee5e913-a30.b-cdn.net/3d246838-2ef4-4487-9ef7-061d57f6dc98/thumbnail.jpg",
            viewCount: 0,
            thumbnailM: null,
            description: [
              "Follow us:\nWebsite: https://www.carlist.my\nFacebook: https://www.facebook.com/Carlist.my\nInstagram: https://www.instagram.com/carlistmy\nTiktok: https://www.tiktok.com/@carlistmy\nCarTell: https://www.facebook.com/groups/cartell",
            ],
            descritptionText:
              "Follow us:\nWebsite: https://www.carlist.my\nFacebook: https://www.facebook.com/Carlist.my\nInstagram: https://www.instagram.com/carlistmy\nTiktok: https://www.tiktok.com/@carlistmy\nCarTell: https://www.facebook.com/groups/cartell",
            slug: "follow-us-website-httpswwwcarlistmy-facebook-fe03",
            linkoutId: null,
            clickableUrl: null,
            linkouts: [],
            isPinned: false,
            thumbnailSprite: null,
            cardLayoutId: 1,
            videoLayoutId: 1,
            duration: 51,
            attributes: null,
            placement_card_layout_id: null,
            placement_video_layout_id: null,
            placement_card_section_layout_id: null,
          },
          group: {
            id: "20da9771-cbef-4be7-87cb-11739d4bed29",
            slug: "car-care-gurus",
            description:
              "Keep it mint! Tips on detailing, DIY maintenance, and the best products for interior & exterior care.",
            shareUrl: "https://tsilrac.qa.begenuin.com/loop/car-care-gurus?community=1fa079ce3e000d64",
            name: "Car Care Gurus",
            isSubscribed: false,
            role: "UNJOINED",
            isPrivate: false,
          },
          community: {
            id: "18195045-22cb-49d3-b466-6d71dd995e05",
            shareUrl: "https://tsilrac.qa.begenuin.com/community/car-gurus-malaysia",
            slug: "car-gurus-malaysia",
            handle: "cargurusmalaysia",
            isPrivate: false,
            userRole: "UNJOINED",
            type: 1,
            name: "🚗 Car Gurus Malaysia",
            profileImage: null,
            membersCount: 8,
            groupsCount: 5,
            postsCount: 49,
            brand: {
              id: 3075,
              name: "Carlist",
              slug: "carlist-vu9m",
              webLogo: "https://media.qa.begenuin.com/uploads/brands/web_logo/Carlist_weblogo_1748946784.png",
              userLogo: 2,
              handle: "Carlistmy",
            },
          },
          owner: {
            profileImage: "https://media.qa.begenuin.com/uploads/profile_images/s/brandProfileLogo_1748947686562.png",
            isAvatar: false,
            userName: "Carlistmy",
            name: "Carlist",
            bio: null,
            shareUrl: "https://tsilrac.qa.begenuin.com/profile/Carlistmy",
            brand: {
              id: 3075,
              slug: "carlist-vu9m",
              userLogo: 2,
            },
          },
          section: {
            id: null,
            title: null,
            description: null,
            position: null,
            thumbnail_url: null,
            cover_url: null,
            no_of_clips: null,
          },
        },
      ],
      hasSection: false,
      pageSession: "slHjmVSAfZBG8",
      endOfFeed: true,
      timestamp: 0,
      totalVideos: undefined,
    },
  ],
  pageParams: [null],
};
