import type { Layout } from "../types";

/**
 * 1024 px breakpoint — 2-column small desktop.
 *
 * Ported verbatim from `Downloads/genuin/grid/layouts/1024.json`.
 * Non-video slots renamed to `Linkout - …` per the porting rule.
 */
export const layout1024: Layout = {
  width: 1024,
  columns: 2,
  pageWidth: 1024,
  colWidths: [664, 312],
  rowHeights: [43, 325, 283, 243, 526, 243, 256, 399, 243, 2408, 243, 188, 347, 188, 347, 376],
  colGap: 48,
  rowGap: 29,
  slots: [
    {
      id: "A1",
      row: 1,
      col: 1,
      name: "Feed Parameters",
      w: 1019,
      h: 43,
      colSpan: 2,
    },
    {
      id: "B1",
      row: 2,
      col: 1,
      name: "Video Placement (Carousel)",
      w: 666,
      h: 614,
      rowSpan: 2,
      carousel: true,
      cols: 2,
    },
    {
      id: "B2",
      row: 2,
      col: 2,
      name: "Linkout - M (Single View)",
      w: 312,
      h: 325,
    },
    {
      id: "C2",
      row: 3,
      col: 2,
      name: "Linkout - S (List View)",
      w: 312,
      h: 283,
      grid: true,
      cols: 1,
      rows: 2,
    },
    {
      id: "D1",
      row: 4,
      col: 1,
      name: "Linkout - M (Grid View)",
      w: 1019,
      h: 243,
      colSpan: 2,
      grid: true,
      cols: 3,
      rows: 1,
    },
    {
      id: "E1",
      row: 5,
      col: 1,
      name: "AI Response",
      w: 666,
      h: 572,
    },
    {
      id: "E2",
      row: 5,
      col: 2,
      name: "Video Placement (Feed)",
      w: 312,
      h: 481,
      floater: true,
    },
    {
      id: "F1",
      row: 6,
      col: 1,
      name: "Linkout - M (Grid View)",
      w: 670,
      h: 243,
      grid: true,
      cols: 2,
      rows: 1,
    },
    {
      id: "G1",
      row: 7,
      col: 1,
      name: "AI Response",
      w: 312,
      h: 513,
      rowSpan: 2,
    },
    {
      id: "H2",
      row: 8,
      col: 2,
      name: "Linkout - S (List View)",
      w: 312,
      h: 399,
      grid: true,
      cols: 1,
      rows: 3,
    },
    {
      id: "I1",
      row: 9,
      col: 1,
      name: "Linkout - M (Grid View)",
      w: 666,
      h: 243,
      grid: true,
      cols: 2,
      rows: 1,
    },
    {
      id: "J1",
      row: 10,
      col: 1,
      name: "Video Placement (Grid)",
      w: 1019,
      h: 2408,
      colSpan: 2,
      grid: true,
      cols: 3,
      rows: 4,
    },
    {
      id: "K1",
      row: 11,
      col: 1,
      name: "Linkout - M (Grid View)",
      w: 1019,
      h: 243,
      colSpan: 2,
      grid: true,
      cols: 3,
      rows: 1,
    },
    {
      id: "L1",
      row: 12,
      col: 1,
      name: "Linkout - M (Grid View)",
      w: 662,
      h: 376,
      rowSpan: 2,
      grid: true,
      cols: 2,
      rows: 1,
    },
    {
      id: "M2",
      row: 13,
      col: 2,
      name: "Linkout - S (List View)",
      w: 304,
      h: 347,
      grid: true,
      cols: 1,
      rows: 3,
    },
    {
      id: "N1",
      row: 14,
      col: 1,
      name: "Linkout - M (Grid View)",
      w: 662,
      h: 376,
      rowSpan: 2,
      grid: true,
      cols: 2,
      rows: 1,
    },
    {
      id: "O2",
      row: 15,
      col: 2,
      name: "Linkout - S (List View)",
      w: 304,
      h: 347,
      grid: true,
      cols: 1,
      rows: 3,
    },
    {
      id: "P1",
      row: 16,
      col: 1,
      name: "Linkout - M (Grid View)",
      w: 662,
      h: 376,
      grid: true,
      cols: 2,
      rows: 1,
    },
  ],
};
