import type { Layout } from "../types";

/**
 * 1280 px breakpoint — 3-column desktop.
 *
 * Ported verbatim from `Downloads/genuin/grid/layouts/1280.json`.
 * Non-video slots renamed to `Linkout - …` per the porting rule.
 */
export const layout1280: Layout = {
  width: 1280,
  columns: 3,
  pageWidth: 1280,
  colWidths: [398, 398, 398],
  rowHeights: [43, 325, 283, 243, 572, 243, 256, 399, 243, 2408, 243, 188, 347, 188, 347, 376],
  colGap: 43,
  rowGap: 26,
  slots: [
    {
      id: "A1",
      row: 1,
      col: 1,
      name: "Feed Parameters",
      w: 1275,
      h: 43,
      colSpan: 3,
    },
    {
      id: "B1",
      row: 2,
      col: 1,
      name: "Video Placement (Carousel)",
      w: 836,
      h: 614,
      colSpan: 2,
      rowSpan: 2,
      carousel: true,
      cols: 2,
    },
    {
      id: "B3",
      row: 2,
      col: 3,
      name: "Linkout - M (Single View)",
      w: 398,
      h: 325,
    },
    {
      id: "C3",
      row: 3,
      col: 3,
      name: "Linkout - S (List View)",
      w: 398,
      h: 283,
      grid: true,
      cols: 1,
      rows: 2,
    },
    {
      id: "D1",
      row: 4,
      col: 1,
      name: "Linkout - M (Grid View)",
      w: 1275,
      h: 243,
      colSpan: 3,
      grid: true,
      cols: 3,
      rows: 1,
    },
    {
      id: "E1",
      row: 5,
      col: 1,
      name: "AI Response",
      w: 836,
      h: 572,
      colSpan: 2,
    },
    {
      id: "E3",
      row: 5,
      col: 3,
      name: "Video Placement (Feed)",
      w: 398,
      h: 572,
      floater: true,
    },
    {
      id: "F1",
      row: 6,
      col: 1,
      name: "Linkout - M (Grid View)",
      w: 840,
      h: 243,
      colSpan: 2,
      grid: true,
      cols: 2,
      rows: 1,
    },
    {
      id: "G1",
      row: 7,
      col: 1,
      name: "Linkout - M (Single View)",
      w: 398,
      h: 513,
      rowSpan: 2,
    },
    {
      id: "H2",
      row: 8,
      col: 2,
      name: "Linkout - S (List View)",
      w: 398,
      h: 399,
      grid: true,
      cols: 1,
      rows: 3,
    },
    {
      id: "I1",
      row: 9,
      col: 1,
      name: "Linkout - M (Grid View)",
      w: 836,
      h: 243,
      colSpan: 2,
      grid: true,
      cols: 2,
      rows: 1,
    },
    {
      id: "J1",
      row: 10,
      col: 1,
      name: "Video Placement (Grid)",
      w: 1275,
      h: 2408,
      colSpan: 3,
      grid: true,
      cols: 3,
      rows: 3,
    },
    {
      id: "K1",
      row: 11,
      col: 1,
      name: "Linkout - M (Grid View)",
      w: 1275,
      h: 243,
      colSpan: 3,
      grid: true,
      cols: 3,
      rows: 1,
    },
    {
      id: "L1",
      row: 12,
      col: 1,
      name: "Linkout - M (Grid View)",
      w: 832,
      h: 376,
      colSpan: 2,
      rowSpan: 2,
      grid: true,
      cols: 2,
      rows: 1,
    },
    {
      id: "M3",
      row: 13,
      col: 3,
      name: "Linkout - S (List View)",
      w: 390,
      h: 347,
      grid: true,
      cols: 1,
      rows: 3,
    },
    {
      id: "N1",
      row: 14,
      col: 1,
      name: "Linkout - M (Grid View)",
      w: 832,
      h: 376,
      colSpan: 2,
      rowSpan: 2,
      grid: true,
      cols: 2,
      rows: 1,
    },
    {
      id: "O3",
      row: 15,
      col: 3,
      name: "Linkout - S (List View)",
      w: 390,
      h: 347,
      grid: true,
      cols: 1,
      rows: 3,
    },
    {
      id: "P1",
      row: 16,
      col: 1,
      name: "Linkout - M (Grid View)",
      w: 832,
      h: 376,
      colSpan: 2,
      grid: true,
      cols: 2,
      rows: 1,
    },
  ],
};
