import type { Layout } from "../types";

/**
 * 1512 px breakpoint — 4-column wide desktop.
 *
 * Ported verbatim from `Downloads/genuin/grid/layouts/1512.json`.
 * Non-video slots renamed to `Linkout - …` per the porting rule.
 */
export const layout1512: Layout = {
  width: 1512,
  columns: 4,
  pageWidth: 1512,
  colWidths: [342, 342, 342, 342],
  rowHeights: [43, 343, 249, 243, 644, 243, 358, 447, 243, 1995, 243, 204, 368, 204, 368],
  colGap: 48,
  rowGap: 48,
  slots: [
    {
      id: "A1",
      row: 1,
      col: 1,
      name: "Feed Parameters",
      w: 1512,
      h: 43,
      colSpan: 4,
    },
    {
      id: "B1",
      row: 2,
      col: 1,
      name: "Video Placement (Carousel)",
      w: 1122,
      h: 614,
      colSpan: 3,
      rowSpan: 2,
      carousel: true,
      cols: 3,
    },
    {
      id: "B4",
      row: 2,
      col: 4,
      name: "Linkout - M (Single View)",
      w: 342,
      h: 343,
    },
    {
      id: "C4",
      row: 3,
      col: 4,
      name: "Linkout - S (List View)",
      w: 342,
      h: 249,
      grid: true,
      cols: 1,
      rows: 2,
    },
    {
      id: "D1",
      row: 4,
      col: 1,
      name: "Linkout - M (Grid View)",
      w: 1512,
      h: 243,
      colSpan: 4,
      grid: true,
      cols: 4,
      rows: 1,
    },
    {
      id: "E1",
      row: 5,
      col: 1,
      name: "AI Response",
      w: 1122,
      h: 758,
      colSpan: 3,
    },
    {
      id: "E4",
      row: 5,
      col: 4,
      name: "Video Placement (Feed)",
      w: 342,
      h: 529,
      floater: true,
    },
    {
      id: "F1",
      row: 6,
      col: 1,
      name: "Linkout - M (Grid View)",
      w: 1122,
      h: 243,
      colSpan: 3,
      grid: true,
      cols: 3,
      rows: 1,
    },
    {
      id: "G1",
      row: 7,
      col: 1,
      name: "AI Response",
      w: 732,
      h: 716,
      colSpan: 2,
      rowSpan: 2,
    },
    {
      id: "H3",
      row: 8,
      col: 3,
      name: "Linkout - S (List View)",
      w: 342,
      h: 447,
      grid: true,
      cols: 1,
      rows: 3,
    },
    {
      id: "I1",
      row: 9,
      col: 1,
      name: "Linkout - M (Grid View)",
      w: 1122,
      h: 243,
      colSpan: 3,
      grid: true,
      cols: 3,
      rows: 1,
    },
    {
      id: "J1",
      row: 10,
      col: 1,
      name: "Video Placement (Grid)",
      w: 1512,
      h: 1995,
      colSpan: 4,
      grid: true,
      cols: 4,
      rows: 3,
    },
    {
      id: "K1",
      row: 11,
      col: 1,
      name: "Linkout - M (Grid View)",
      w: 1512,
      h: 243,
      colSpan: 4,
      grid: true,
      cols: 4,
      rows: 1,
    },
    {
      id: "L1",
      row: 12,
      col: 1,
      name: "Linkout - M (Grid View)",
      w: 1122,
      h: 409,
      colSpan: 3,
      rowSpan: 2,
      grid: true,
      cols: 3,
      rows: 1,
    },
    {
      id: "M4",
      row: 13,
      col: 4,
      name: "Linkout - S (List View)",
      w: 342,
      h: 368,
      grid: true,
      cols: 1,
      rows: 3,
    },
    {
      id: "N1",
      row: 14,
      col: 1,
      name: "Linkout - M (Grid View)",
      w: 1122,
      h: 409,
      colSpan: 3,
      rowSpan: 2,
      grid: true,
      cols: 3,
      rows: 1,
    },
    {
      id: "O4",
      row: 15,
      col: 4,
      name: "Linkout - S (List View)",
      w: 342,
      h: 368,
      grid: true,
      cols: 1,
      rows: 3,
    },
  ],
};
