import type { Layout } from "../types";

/**
 * 748 px breakpoint — 2-column tablet.
 *
 * Ported verbatim from `Downloads/genuin/grid/layouts/748.json`.
 * Non-video slots renamed to `Linkout - …` per the porting rule.
 */
export const layout748: Layout = {
  width: 748,
  columns: 2,
  pageWidth: 744,
  colWidths: [355, 355],
  rowHeights: [43, 612, 295, 243, 590, 282, 507, 256, 399, 243, 3960, 243, 1363, 386],
  colGap: 34,
  rowGap: 30,
  slots: [
    {
      id: "A1",
      row: 1,
      col: 1,
      name: "Feed Parameters",
      w: 739,
      h: 43,
      colSpan: 2,
    },
    {
      id: "B1",
      row: 2,
      col: 1,
      name: "Video Placement (Carousel)",
      w: 739,
      h: 612,
      colSpan: 2,
      carousel: true,
      cols: 2,
    },
    {
      id: "C1",
      row: 3,
      col: 1,
      name: "Linkout - M (Single View)",
      w: 355,
      h: 329,
    },
    {
      id: "C2",
      row: 3,
      col: 2,
      name: "Linkout - S (List View)",
      w: 355,
      h: 261,
      grid: true,
      cols: 1,
      rows: 2,
    },
    {
      id: "D1",
      row: 4,
      col: 1,
      name: "Linkout - M (Grid View)",
      w: 739,
      h: 243,
      colSpan: 2,
      grid: true,
      cols: 2,
      rows: 1,
    },
    {
      id: "E1",
      row: 5,
      col: 1,
      name: "AI Response",
      w: 739,
      h: 590,
      colSpan: 2,
    },
    {
      id: "F2",
      row: 6,
      col: 2,
      name: "Video Placement (Feed)",
      w: 355,
      h: 565,
      rowSpan: 2,
    },
    {
      id: "G1",
      row: 7,
      col: 1,
      name: "Linkout - S (List View)",
      w: 355,
      h: 507,
      grid: true,
      cols: 1,
      rows: 2,
    },
    {
      id: "H1",
      row: 8,
      col: 1,
      name: "Linkout - M (Single View)",
      w: 355,
      h: 513,
      rowSpan: 2,
    },
    {
      id: "I2",
      row: 9,
      col: 2,
      name: "Linkout - S (List View)",
      w: 355,
      h: 399,
      grid: true,
      cols: 1,
      rows: 3,
    },
    {
      id: "J1",
      row: 10,
      col: 1,
      name: "Linkout - M (Grid View)",
      w: 739,
      h: 243,
      colSpan: 2,
      grid: true,
      cols: 2,
      rows: 1,
    },
    {
      id: "K1",
      row: 11,
      col: 1,
      name: "Video Placement (Grid)",
      w: 739,
      h: 3960,
      colSpan: 2,
      grid: true,
      cols: 2,
      rows: 6,
    },
    {
      id: "L1",
      row: 12,
      col: 1,
      name: "Linkout - M (Grid View)",
      w: 739,
      h: 243,
      colSpan: 2,
      grid: true,
      cols: 2,
      rows: 1,
    },
    {
      id: "M1",
      row: 13,
      col: 1,
      name: "Linkout - M (Grid View)",
      w: 739,
      h: 1363,
      colSpan: 2,
      grid: true,
      cols: 2,
      rows: 3,
    },
    {
      id: "N1",
      row: 14,
      col: 1,
      name: "Linkout - M (Grid View)",
      w: 739,
      h: 386,
      colSpan: 2,
      grid: true,
      cols: 2,
      rows: 3,
    },
  ],
};
