/**
 * @fileoverview Page navigation helper for SDK E2E tests.
 *
 * Provides a single function to load the test HTML page and wait for the SDK
 * script to be available on `window.genuin` before tests interact with it.
 *
 * @author Genuin Team
 */

import type { Page } from "@playwright/test";

import { waitForSDK } from "./sdk-wait.helper";

/**
 * Navigate to the test page and wait for the SDK to be ready.
 *
 * Loads `index-test.html` (auto-generated by global-setup.ts) which includes
 * the built `dist/gen_sdk.js` script. Waits until `window.genuin` is defined
 * before returning, ensuring tests can safely call SDK methods.
 *
 * @param page - Playwright Page instance
 */
export async function loadTestPage(page: Page) {
  await page.goto("/index-test.html");

  await waitForSDK(page);
}
