import type { Preview } from "@storybook/react-vite";

import "../src/globals.css";
import { AuthProvider } from "../src/context/auth";
import {
  BaseContextProvider,
  DEFAULT_BRAND_DETAILS,
} from "../src/context/base";
import { parseBrandColors } from "../src/lib/utils/brand-color-parser";
import { ReactQueryClientProvider } from "../src/react-query/react-query-provider";

const brandDetails = {
  brand_id: 2260,
  type: 1,
  is_claimed: true,
  website: "https://www.skoda-auto.co.in/",
  name: "Skoda",
  status: 1,
  subdomain: "vkleowon",
  logo: "https://media.qa.begenuin.com/uploads/brands/logo/brandProfileLogo_1734514054853.png",
  created_at: 1730789182444,
  integrations: {
    sdk: {
      web: {
        enable: true,
        hide_navbar: true,
      },
      android: {
        enable: true,
        playstore_link:
          "https://play.google.com/store/apps/details?id=cz.skodaauto.myskoda&hl=en_US&pli=1",
      },
      ios: {
        enable: true,
        appstore_link:
          "https://apps.apple.com/in/app/my%C5%A1koda/id1147949033",
      },
    },
    white_label: {
      enable: false,
      allowed_domains: [],
      test_allowed_domains: [],
    },
  },
  brand_colors: {
    primary: {
      primary_100: "#f1f6ec",
      primary_200: "#e3edd9",
      primary_300: "#b9d2a0",
      primary_400: "#9dc079",
      primary: "#73a540",
      primary_600: "#51732d",
      primary_700: "#3a5320",
    },
  },
  brand_web_logo:
    "https://media.qa.begenuin.com/uploads/brands/web_logo/brandWebLogo_1730789229185.png",
  favicon:
    "https://media.qa.begenuin.com/uploads/brands/favicon/brandFavicon_1730789242942.png",
  is_wallet_enabled: false,
  global_reward_point_configs: {
    view: 1,
    spark: 1,
    comments: 1,
    repost: 1,
  },
  social_login: {
    google: true,
    apple: true,
    brand: false,
    brand_sso_id: null,
  },
  web_cta: "login",
  is_interruption_disabled: false,
  show_become_creator: true,
  api_key: "e895c22b1281e14ff16405aa54f1d68ac6238de9b709383c",
  reactions: {
    type: "spark",
    title: "react",
    suffix: "to",
    keys: {
      comment_selected: {
        png: "https://media.qa.begenuin.com/webapp_assets/reactions/spark/comment_selected.png",
        svg: "https://media.qa.begenuin.com/webapp_assets/reactions/spark/comment_selected.svg",
      },
      comment_unselected: {
        png: "https://media.qa.begenuin.com/webapp_assets/reactions/spark/comment_unselected.png",
        svg: "https://media.qa.begenuin.com/webapp_assets/reactions/spark/comment_unselected.svg",
      },
      feed_animate: {
        png: "https://media.qa.begenuin.com/webapp_assets/reactions/spark/feed_animate.png",
        svg: "https://media.qa.begenuin.com/webapp_assets/reactions/spark/feed_animate.svg",
      },
      feed_selected: {
        png: "https://media.qa.begenuin.com/webapp_assets/reactions/spark/feed_selected.png",
        svg: "https://media.qa.begenuin.com/webapp_assets/reactions/spark/feed_selected.svg",
      },
      feed_unselected: {
        png: "https://media.qa.begenuin.com/webapp_assets/reactions/spark/feed_unselected.png",
        svg: "https://media.qa.begenuin.com/webapp_assets/reactions/spark/feed_unselected.svg",
      },
    },
    tooltip: "I find this insightful",
  },
  privacy_policy: null,
  industry_type: 4,
  terms_and_condition: null,
  mobile_configs: {
    video_autoplay: {
      type: 1,
      auto_play_after: 5,
    },
    feed_video_play: {
      type: 1,
      repeat_video: 0,
      swipe_after: 0,
    },
    linkout_delay: {
      type: 1,
      appear_after: 10,
    },
    login_signup_popup: {
      enable: true,
      popup_after: 5,
    },
    interest_selection_popup: {
      enable: true,
      popup_after: 5,
    },
    username_popup: {
      enable: true,
      popup_after: 5,
    },
    complete_profile_popup: {
      enable: true,
      popup_after: 5,
    },
    idle_time_interruption: {
      enable: false,
      popup_after: 60,
    },
    playback_speed_enabled: false,
    video_aspect_ratio: "9:16",
    tap_behavior: 1,
    share_transcript_enabled: false,
    gesture_guidance: false,
    is_start_with_sound: true,
  },
  web_configs: {
    video_autoplay: {
      type: 1,
      auto_play_after: 5,
    },
    feed_video_play: {
      type: 1,
      repeat_video: 0,
      swipe_after: 1,
    },
    linkout_delay: {
      type: 1,
      appear_after: 10,
    },
    get_app_popup: {
      enable: true,
      popup_after: 5,
    },
    login_signup_popup: {
      enable: true,
      popup_after: 5,
    },
    interest_selection_popup: {
      enable: true,
      popup_after: 5,
    },
    username_popup: {
      enable: true,
      popup_after: 5,
    },
    complete_profile_popup: {
      enable: true,
      popup_after: 5,
    },
    idle_time_interruption: {
      enable: true,
      popup_after: 60,
    },
    video_aspect_ratio: "9:16",
    tap_behavior: 2,
    gesture_guidance: true,
    playback_speed_enabled: false,
    is_start_with_sound: false,
    share_transcript_enabled: false,
  },
  sitemap_configs: {
    robots_config: [],
    asset_links_config: [],
  },
  white_label_url: "https://vkleowon.qa.begenuin.com",
  pin_limit: {
    loop: 2,
    loop_videos: 2,
  },
  ad_configs: {
    feed_stream: false,
    in_video_stream: false,
  },
  comment_type: {
    text: true,
    video: true,
    audio: true,
  },
  camera_enabled: true,
  default_embeds: [
    {
      _id: "67a9c4322db4480e8e1fadff",
      name: "Home/Search Embed",
      style: "carousel",
      type: "brand_feed",
      brand_id: 2260,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        cta_button: {
          text: "Explore More",
          url: "https://google.com",
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        links: {
          is_show_links: true,
          position: "outside",
        },
        carousel_style: "default",
        autoplay: true,
        heading: "Specials",
        sub_heading: "Discover what's popular in your community",
        is_carousel_icon: false,
        is_floating_view: false,
        is_show_username: true,
        is_show_view_count: true,
        is_enable_engagement_tools: true,
        is_loop_video: false,
        is_show_social_interaction_data: true,
        community_ids: [],
        community_loop_ids: [],
        feed_display_pref: "default",
      },
      __v: 0,
    },
    {
      _id: "67a9c4322db4480e8e1fae00",
      name: "Blog Embed",
      style: "feed",
      type: "brand_feed",
      brand_id: 2260,
      is_default: true,
      customization: {
        dimensions: {
          width: 300,
          height: 600,
        },
        cta_button: {
          text: "",
          url: "",
          color: "#023F9A",
          text_color: "#023F9A",
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        enable_redirection_tools: {
          community: false,
          group: false,
          user: false,
        },
        links: {
          is_show_links: false,
          position: "overlay",
        },
        carousel_style: "default",
        autoplay: true,
        heading: "Insider Info",
        heading_text_color: "#212529",
        sub_heading: "Discover what's popular in your community",
        sub_heading_text_color: "#6C757D",
        is_floating_view: true,
        is_expanded_view: false,
        is_show_username: false,
        is_show_view_count: true,
        is_enable_engagement_tools: true,
        show_side_panel: false,
        show_join_community_button: false,
        show_community_share_button: false,
        is_enable_redirection: false,
        is_loop_video: false,
        is_show_social_interaction_data: false,
        community_ids: [],
        is_popup_view: true,
        community_loop_ids: [],
        feed_display_pref: "default",
      },
      __v: 0,
    },
    {
      _id: "67a9c4322db4480e8e1fae01",
      name: "Home/Search Embed1",
      style: "feed",
      type: "brand_feed",
      brand_id: 2260,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        enable_redirection_tools: {
          community: false,
          group: false,
          user: false,
        },
        links: {
          is_show_links: false,
          position: "overlay",
        },
        carousel_style: "default",
        autoplay: true,
        is_floating_view: false,
        is_expanded_view: false,
        is_show_username: false,
        is_show_view_count: true,
        is_enable_engagement_tools: true,
        show_side_panel: false,
        show_join_community_button: false,
        show_community_share_button: false,
        is_enable_redirection: false,
        is_loop_video: false,
        is_show_social_interaction_data: false,
        community_ids: [],
        community_loop_ids: [],
        feed_display_pref: "default",
      },
      __v: 0,
    },
    {
      _id: "67a9c4322db4480e8e1fae02",
      name: "Post-Sales Embed",
      style: "carousel",
      type: "brand_feed",
      brand_id: 2260,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        links: {
          is_show_links: true,
          position: "overlay",
        },
        carousel_style: "default",
        autoplay: false,
        heading: "Reviews for you",
        sub_heading: "See what others are getting",
        is_carousel_icon: false,
        is_floating_view: false,
        is_show_username: false,
        is_show_view_count: false,
        is_enable_engagement_tools: true,
        show_side_panel: true,
        is_loop_video: true,
        is_show_social_interaction_data: false,
        community_ids: [],
        community_loop_ids: [],
        feed_display_pref: "default",
      },
      __v: 0,
    },
    {
      _id: "67a9c4322db4480e8e1fae03",
      name: "PDP Embed",
      style: "carousel",
      type: "brand_feed",
      brand_id: 2260,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        links: {
          is_show_links: true,
          position: "overlay",
        },
        carousel_style: "default",
        autoplay: true,
        heading: "Reviews for you",
        sub_heading: "Discover what's popular in your community",
        is_carousel_icon: false,
        is_floating_view: false,
        is_show_username: false,
        is_show_view_count: true,
        is_enable_engagement_tools: true,
        is_loop_video: false,
        is_show_social_interaction_data: false,
        community_ids: [],
        community_loop_ids: [],
        feed_display_pref: "default",
      },
      __v: 0,
    },
    {
      _id: "67a9c4322db4480e8e1fae04",
      name: "Home/Blog Embed",
      style: "carousel",
      type: "brand_feed",
      brand_id: 2260,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        links: {
          is_show_links: true,
          position: "overlay",
        },
        carousel_style: "default",
        autoplay: true,
        is_carousel_icon: false,
        is_floating_view: false,
        is_show_username: false,
        is_show_view_count: true,
        is_enable_engagement_tools: true,
        is_loop_video: false,
        is_show_social_interaction_data: false,
        community_ids: [],
        community_loop_ids: [],
        feed_display_pref: "default",
      },
      __v: 0,
    },
    {
      _id: "67c17f9fe0ac202848d7ac5d",
      name: "Blog Embed",
      style: "feed",
      type: "brand_feed",
      brand_id: 2260,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        enable_redirection_tools: {
          community: false,
          group: false,
          user: false,
        },
        links: {
          is_show_links: false,
          position: "overlay",
        },
        carousel_style: "default",
        autoplay: true,
        heading: "Insider Info",
        sub_heading: "Discover what's popular in your community",
        is_floating_view: true,
        is_expanded_view: false,
        is_show_username: false,
        is_show_view_count: true,
        is_enable_engagement_tools: true,
        show_side_panel: false,
        show_join_community_button: false,
        show_community_share_button: false,
        is_enable_redirection: false,
        is_loop_video: false,
        is_show_social_interaction_data: false,
        community_ids: [],
        community_loop_ids: [],
        feed_display_pref: "default",
      },
      __v: 0,
    },
    {
      _id: "67c17f9fe0ac202848d7ac5c",
      name: "Home/Search Embed",
      style: "carousel",
      type: "brand_feed",
      brand_id: 2260,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        cta_button: {
          text: "Explore More",
          url: "https://google.com",
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        links: {
          is_show_links: true,
          position: "outside",
        },
        carousel_style: "default",
        autoplay: true,
        heading: "Specials",
        sub_heading: "Discover what's popular in your community",
        is_carousel_icon: false,
        is_floating_view: false,
        is_show_username: true,
        is_show_view_count: true,
        is_enable_engagement_tools: true,
        is_loop_video: false,
        is_show_social_interaction_data: true,
        community_ids: [],
        community_loop_ids: [],
        feed_display_pref: "default",
      },
      __v: 0,
    },
    {
      _id: "67c17f9fe0ac202848d7ac60",
      name: "PDP Embed",
      style: "carousel",
      type: "brand_feed",
      brand_id: 2260,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        links: {
          is_show_links: true,
          position: "overlay",
        },
        carousel_style: "default",
        autoplay: true,
        heading: "Reviews for you",
        sub_heading: "Discover what's popular in your community",
        is_carousel_icon: false,
        is_floating_view: false,
        is_show_username: false,
        is_show_view_count: true,
        is_enable_engagement_tools: true,
        is_loop_video: false,
        is_show_social_interaction_data: false,
        community_ids: [],
        community_loop_ids: [],
        feed_display_pref: "default",
      },
      __v: 0,
    },
    {
      _id: "67c17f9fe0ac202848d7ac5e",
      name: "Home/Search Embed1",
      style: "feed",
      type: "brand_feed",
      brand_id: 2260,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        enable_redirection_tools: {
          community: false,
          group: false,
          user: false,
        },
        links: {
          is_show_links: false,
          position: "overlay",
        },
        carousel_style: "default",
        autoplay: true,
        is_floating_view: false,
        is_expanded_view: false,
        is_show_username: false,
        is_show_view_count: true,
        is_enable_engagement_tools: true,
        show_side_panel: false,
        show_join_community_button: false,
        show_community_share_button: false,
        is_enable_redirection: false,
        is_loop_video: false,
        is_show_social_interaction_data: false,
        community_ids: [],
        community_loop_ids: [],
        feed_display_pref: "default",
      },
      __v: 0,
    },
    {
      _id: "67c17f9fe0ac202848d7ac61",
      name: "Home/Blog Embed",
      style: "carousel",
      type: "brand_feed",
      brand_id: 2260,
      is_default: true,
      customization: {
        dimensions: {
          width: 800,
          height: 600,
        },
        cta_button: {
          text: "",
          url: "",
          color: "#023F9A",
          text_color: "#023F9A",
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        enable_redirection_tools: {
          community: true,
          group: true,
          user: true,
        },
        links: {
          is_show_links: true,
          position: "overlay",
        },
        carousel_style: "default",
        autoplay: true,
        heading: "",
        heading_text_color: "#212529",
        sub_heading: "",
        sub_heading_text_color: "#6C757D",
        is_carousel_icon: false,
        is_floating_view: false,
        is_show_username: false,
        is_show_view_count: true,
        is_enable_engagement_tools: true,
        show_side_panel: true,
        show_join_community_button: true,
        show_community_share_button: true,
        is_enable_redirection: true,
        is_loop_video: false,
        is_show_social_interaction_data: false,
        community_ids: [],
        is_popup_view: false,
        community_loop_ids: [],
        feed_display_pref: "default",
      },
      __v: 0,
      is_live: true,
    },
    {
      _id: "67c17f9fe0ac202848d7ac5f",
      name: "Post-Sales Embed",
      style: "carousel",
      type: "brand_feed",
      brand_id: 2260,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        links: {
          is_show_links: true,
          position: "overlay",
        },
        carousel_style: "default",
        autoplay: false,
        heading: "Reviews for you",
        sub_heading: "See what others are getting",
        is_carousel_icon: false,
        is_floating_view: false,
        is_show_username: false,
        is_show_view_count: false,
        is_enable_engagement_tools: true,
        show_side_panel: true,
        is_loop_video: true,
        is_show_social_interaction_data: false,
        community_ids: [],
        community_loop_ids: [],
        feed_display_pref: "default",
      },
      __v: 0,
    },
    {
      _id: "67c17f9fe0ac202848d7ac62",
      name: "Home/Post Sales Embed",
      style: "standard_wall",
      type: "brand_feed",
      brand_id: 2260,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        enable_redirection_tools: {
          community: true,
          group: true,
          user: true,
        },
        links: {
          is_show_links: true,
        },
        show_navigation: true,
        carousel_style: "default",
        is_enable_engagement_tools: true,
        show_side_panel: true,
        show_join_community_button: true,
        show_community_share_button: true,
        is_enable_redirection: true,
        is_loop_video: true,
        community_ids: [],
        community_loop_ids: [],
        feed_display_pref: "default",
      },
      __v: 0,
      is_live: true,
    },
  ],
  slogan: {
    text: "Create your own brand",
    image:
      "https://media.qa.begenuin.com/uploads/brands/slogan_image/1f49226365001400.png",
    font: {
      _id: "65f04ccf322929c13ba07082",
      weight: "normal",
      style: "normal",
    },
  },
  environment: "PROD",
};

const preview: Preview = {
  decorators: [
    (Story) => {
      const parsedColor = parseBrandColors(brandDetails.brand_colors);
      return (
        <AuthProvider
        // user={{
        //   id: "e427978f-44db-4a5f-8fb9-2760458027dd",
        //   image: "pile_of_poo",
        //   isAvatar: true,
        //   phoneNumber: null,
        //   nickname: "dhanji",
        //   email: "dhanji@yopmail.com",
        //   bio: null,
        //   name: null,
        //   accessToken:
        //     "eyJraWQiOiJkLTE3NDkyMDE0MzYxMzYiLCJ0eXAiOiJKV1QiLCJ2ZXJzaW9uIjoiNSIsImFsZyI6IlJTMjU2In0.eyJpYXQiOjE3NDk1NTc3ODMsImV4cCI6MTc1MDc2NzM4Miwic3ViIjoiNjhjMzA4NWUtYTNjMC00ZWViLThhZGUtN2RmOTE2MzViYjhlIiwidElkIjoicHVibGljIiwicnN1YiI6IjY4YzMwODVlLWEzYzAtNGVlYi04YWRlLTdkZjkxNjM1YmI4ZSIsInNlc3Npb25IYW5kbGUiOiI2NWNjYjE5MC1iMWFiLTQwMjQtYmUyNC1hMjUzNGEzMDc3MjQiLCJyZWZyZXNoVG9rZW5IYXNoMSI6ImE3N2JjMmVmMmU4ZWM4NzE1ODdlNjk3MTkwMmY0ZDE4OWQ3YzNhYjQ4NjllNGJkMzE1NjkwODAwZTFkZDQ1NTIiLCJwYXJlbnRSZWZyZXNoVG9rZW5IYXNoMSI6bnVsbCwiYW50aUNzcmZUb2tlbiI6bnVsbCwiaXNzIjoiaHR0cHM6Ly9ub2RlanMucWEuYmVnZW51aW4uY29tL2FwaS92NC9hdXRoIiwic3Qtcm9sZSI6eyJ2IjpbXSwidCI6MTc0OTU1Nzc4MjYzNn0sInN0LXBlcm0iOnsidiI6W10sInQiOjE3NDk1NTc3ODI2MzZ9LCJnZW51aW4iOnsidXNlcl9pZCI6ImU0Mjc5NzhmLTQ0ZGItNGE1Zi04ZmI5LTI3NjA0NTgwMjdkZCIsImxvZ2luX3NvdXJjZSI6MywiZGV2aWNlX3R5cGUiOiJ3ZWIiLCJicmFuZF9pZCI6MjkyMn19.BOIOF-_sUEQVX6ow-vSgxKhwse7TGJWrMHrim32ZLLDi3B9TmImoW20Nq5ld7AFExzNb1Bu1K7Muph_H7bLE4GeqyLAo5z0mzi9YKe4yREf3xGevN3LvLTeE1q3zJHFgfMqH_CDnfYYOH78r82LE-iKTczEketbKknB5rwuoptsFLcduyfDsphT3W5WQblMAkr_c6LVEid9SiNTrq3lXgRbVQRe5rmf7EpI_vJ_A2zFkoHCv9VkEcIeUhgKfoOKXyqxGbWL41aNpJEJ57nTbMjxOPpxWF_tu7a3ohSrBwUhCOpyQ4fxoyNG7XS5fbWNIMkv4JTUmDVGtnFWpHiXPjw",
        //   ksCbRequestStatus: 1,
        //   isBrandSystemUser: false,
        //   brandId: 2922,
        //   brandSlug: null,
        //   hasTopics: false,
        //   brandGuidelines: false,
        //   refreshToken:
        //     "H6uCa5yhYXitof+PUxKv6uTc+ccgMJqjlk8f9cRx+doS+qacDeZqPWZgpr3E8S4e67pd1Eqs0L0HH2Amj6XuJwxFCix4aGr5w2aY8b7Qe60oSkr5uSUencEPInuQEqGfQrzTmg9RFtBV1VnVsFedo7xfcwSuQTBdfCW6xT3XDfY455K1IyP96CnO9eJJAs4pyKo+zIQ5po70z3W7p8y3oghNobWPl571lSnFrg5vsavvKFnjAs3CVAQeuQNYl0+CXk952/Ug6LV1sUbvR78U.ec84a0e2f0af57d23c844f3f2f46df05ce96dd342b38f56ab27c02c018ad1741.V2",
        //   usernameSet: false,
        // }}
        >
          <BaseContextProvider brandDetails={brandDetails}>
            <ReactQueryClientProvider>
              <main style={{ ...parsedColor }}>
                <Story />
              </main>
            </ReactQueryClientProvider>
          </BaseContextProvider>
        </AuthProvider>
      );
    },
  ],
  parameters: {
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },
    },
  },
};

export default preview;
