import type { Preview } from "@storybook/react-vite";

import "../src/globals.css";
import { AuthProvider } from "../src/context/auth";
import {
  BaseContextProvider,
  DEFAULT_BRAND_DETAILS,
} from "../src/context/base";
import { parseBrandColors } from "../src/lib/utils/brand-color-parser";
import { ReactQueryClientProvider } from "../src/react-query/react-query-provider";
import { Toaster } from "@genuin/ui/toaster";

const brandDetails = {
  brand_id: 2260,
  type: 1,
  is_claimed: true,
  website: "https://www.skoda-auto.co.in/",
  name: "Skoda",
  status: 1,
  subdomain: "vkleowon",
  logo: "https://media.qa.begenuin.com/uploads/brands/logo/brandProfileLogo_1734514054853.png",
  created_at: 1730789182444,
  integrations: {
    sdk: {
      web: {
        enable: true,
        hide_navbar: true,
      },
      android: {
        enable: true,
        playstore_link:
          "https://play.google.com/store/apps/details?id=cz.skodaauto.myskoda&hl=en_US&pli=1",
      },
      ios: {
        enable: true,
        appstore_link:
          "https://apps.apple.com/in/app/my%C5%A1koda/id1147949033",
      },
    },
    white_label: {
      enable: false,
      allowed_domains: [],
      test_allowed_domains: [],
    },
  },
  brand_colors: {
    primary: {
      primary_100: "#f1f6ec",
      primary_200: "#e3edd9",
      primary_300: "#b9d2a0",
      primary_400: "#9dc079",
      primary: "#73a540",
      primary_600: "#51732d",
      primary_700: "#3a5320",
    },
  },
  brand_web_logo:
    "https://media.qa.begenuin.com/uploads/brands/web_logo/brandWebLogo_1730789229185.png",
  favicon:
    "https://media.qa.begenuin.com/uploads/brands/favicon/brandFavicon_1730789242942.png",
  is_wallet_enabled: false,
  global_reward_point_configs: {
    view: 1,
    spark: 1,
    comments: 1,
    repost: 1,
  },
  social_login: {
    google: true,
    apple: true,
    brand: false,
    brand_sso_id: null,
  },
  web_cta: "login",
  is_interruption_disabled: false,
  show_become_creator: true,
  api_key: "e895c22b1281e14ff16405aa54f1d68ac6238de9b709383c",
  reactions: {
    type: "thumbs_up",
    title: "react",
    suffix: "to",
    keys: {
      comment_selected: {
        png: "https://media.qa.begenuin.com/webapp_assets/reactions/thumbs_up/comment_selected.png",
        svg: "https://media.qa.begenuin.com/webapp_assets/reactions/thumbs_up/comment_selected.svg",
      },
      comment_unselected: {
        png: "https://media.qa.begenuin.com/webapp_assets/reactions/thumbs_up/comment_unselected.png",
        svg: "https://media.qa.begenuin.com/webapp_assets/reactions/thumbs_up/comment_unselected.svg",
      },
      feed_animate: {
        png: "https://media.qa.begenuin.com/webapp_assets/reactions/thumbs_up/feed_animate.png",
        svg: "https://media.qa.begenuin.com/webapp_assets/reactions/thumbs_up/feed_animate.svg",
      },
      feed_selected: {
        png: "https://media.qa.begenuin.com/webapp_assets/reactions/thumbs_up/feed_selected.png",
        svg: "https://media.qa.begenuin.com/webapp_assets/reactions/thumbs_up/feed_selected.svg",
      },
      feed_unselected: {
        png: "https://media.qa.begenuin.com/webapp_assets/reactions/thumbs_up/feed_unselected.png",
        svg: "https://media.qa.begenuin.com/webapp_assets/reactions/thumbs_up/feed_unselected.svg",
      },
    },
    tooltip: "I like this!",
  },
  privacy_policy: null,
  industry_type: 4,
  terms_and_condition: null,
  mobile_configs: {
    video_autoplay: {
      type: 1,
      auto_play_after: 5,
    },
    feed_video_play: {
      type: 1,
      repeat_video: 0,
      swipe_after: 0,
    },
    linkout_delay: {
      type: 1,
      appear_after: 10,
    },
    login_signup_popup: {
      enable: true,
      popup_after: 5,
    },
    interest_selection_popup: {
      enable: true,
      popup_after: 5,
    },
    username_popup: {
      enable: true,
      popup_after: 5,
    },
    complete_profile_popup: {
      enable: true,
      popup_after: 5,
    },
    idle_time_interruption: {
      enable: false,
      popup_after: 60,
    },
    playback_speed_enabled: true,
    video_aspect_ratio: "9:16",
    tap_behavior: 1,
    share_transcript_enabled: false,
    gesture_guidance: false,
    is_start_with_sound: true,
  },
  web_configs: {
    video_autoplay: {
      type: 1,
      auto_play_after: 5,
    },
    feed_video_play: {
      type: 1,
      repeat_video: 0,
      swipe_after: 1,
    },
    linkout_delay: {
      type: 1,
      appear_after: 10,
    },
    get_app_popup: {
      enable: true,
      popup_after: 5,
    },
    login_signup_popup: {
      enable: true,
      popup_after: 5,
    },
    interest_selection_popup: {
      enable: true,
      popup_after: 5,
    },
    username_popup: {
      enable: true,
      popup_after: 5,
    },
    complete_profile_popup: {
      enable: true,
      popup_after: 5,
    },
    idle_time_interruption: {
      enable: true,
      popup_after: 60,
    },
    video_aspect_ratio: "9:16",
    tap_behavior: 2,
    gesture_guidance: true,
    playback_speed_enabled: true,
    is_start_with_sound: false,
    share_transcript_enabled: false,
  },
  sitemap_configs: {
    robots_config: [],
    asset_links_config: [],
  },
  white_label_url: "https://vkleowon.qa.begenuin.com",
  pin_limit: {
    loop: 2,
    loop_videos: 2,
  },
  ad_configs: {
    feed_stream: false,
    in_video_stream: false,
  },
  comment_type: {
    text: true,
    video: true,
    audio: true,
  },
  camera_enabled: true,
  default_embeds: [
    {
      _id: "67a9c4322db4480e8e1fadff",
      name: "Home/Search Embed",
      style: "carousel",
      type: "brand_feed",
      brand_id: 2260,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        cta_button: {
          text: "Explore More",
          url: "https://google.com",
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        links: {
          is_show_links: true,
          position: "outside",
        },
        carousel_style: "default",
        autoplay: true,
        heading: "Specials",
        sub_heading: "Discover what's popular in your community",
        is_carousel_icon: false,
        is_floating_view: false,
        is_show_username: true,
        is_show_view_count: true,
        is_enable_engagement_tools: true,
        is_loop_video: false,
        is_show_social_interaction_data: true,
        community_ids: [],
        community_loop_ids: [],
        feed_display_pref: "default",
      },
      __v: 0,
    },
    {
      _id: "67a9c4322db4480e8e1fae00",
      name: "Blog Embed",
      style: "feed",
      type: "brand_feed",
      brand_id: 2260,
      is_default: true,
      customization: {
        dimensions: {
          width: 300,
          height: 600,
        },
        cta_button: {
          text: "",
          url: "",
          color: "#023F9A",
          text_color: "#023F9A",
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        enable_redirection_tools: {
          community: false,
          group: false,
          user: false,
        },
        links: {
          is_show_links: false,
          position: "overlay",
        },
        carousel_style: "default",
        autoplay: true,
        heading: "Insider Info",
        heading_text_color: "#212529",
        sub_heading: "Discover what's popular in your community",
        sub_heading_text_color: "#6C757D",
        is_floating_view: true,
        is_expanded_view: false,
        is_show_username: false,
        is_show_view_count: true,
        is_enable_engagement_tools: true,
        show_side_panel: false,
        show_join_community_button: false,
        show_community_share_button: false,
        is_enable_redirection: false,
        is_loop_video: false,
        is_show_social_interaction_data: false,
        community_ids: [],
        is_popup_view: true,
        community_loop_ids: [],
        feed_display_pref: "default",
      },
      __v: 0,
    },
    {
      _id: "67a9c4322db4480e8e1fae01",
      name: "Home/Search Embed1",
      style: "feed",
      type: "brand_feed",
      brand_id: 2260,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        enable_redirection_tools: {
          community: false,
          group: false,
          user: false,
        },
        links: {
          is_show_links: false,
          position: "overlay",
        },
        carousel_style: "default",
        autoplay: true,
        is_floating_view: false,
        is_expanded_view: false,
        is_show_username: false,
        is_show_view_count: true,
        is_enable_engagement_tools: true,
        show_side_panel: false,
        show_join_community_button: false,
        show_community_share_button: false,
        is_enable_redirection: false,
        is_loop_video: false,
        is_show_social_interaction_data: false,
        community_ids: [],
        community_loop_ids: [],
        feed_display_pref: "default",
      },
      __v: 0,
    },
    {
      _id: "67a9c4322db4480e8e1fae02",
      name: "Post-Sales Embed",
      style: "carousel",
      type: "brand_feed",
      brand_id: 2260,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        links: {
          is_show_links: true,
          position: "overlay",
        },
        carousel_style: "default",
        autoplay: false,
        heading: "Reviews for you",
        sub_heading: "See what others are getting",
        is_carousel_icon: false,
        is_floating_view: false,
        is_show_username: false,
        is_show_view_count: false,
        is_enable_engagement_tools: true,
        show_side_panel: true,
        is_loop_video: true,
        is_show_social_interaction_data: false,
        community_ids: [],
        community_loop_ids: [],
        feed_display_pref: "default",
      },
      __v: 0,
    },
    {
      _id: "67a9c4322db4480e8e1fae03",
      name: "PDP Embed",
      style: "carousel",
      type: "brand_feed",
      brand_id: 2260,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        links: {
          is_show_links: true,
          position: "overlay",
        },
        carousel_style: "default",
        autoplay: true,
        heading: "Reviews for you",
        sub_heading: "Discover what's popular in your community",
        is_carousel_icon: false,
        is_floating_view: false,
        is_show_username: false,
        is_show_view_count: true,
        is_enable_engagement_tools: true,
        is_loop_video: false,
        is_show_social_interaction_data: false,
        community_ids: [],
        community_loop_ids: [],
        feed_display_pref: "default",
      },
      __v: 0,
    },
    {
      _id: "67a9c4322db4480e8e1fae04",
      name: "Home/Blog Embed",
      style: "carousel",
      type: "brand_feed",
      brand_id: 2260,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        links: {
          is_show_links: true,
          position: "overlay",
        },
        carousel_style: "default",
        autoplay: true,
        is_carousel_icon: false,
        is_floating_view: false,
        is_show_username: false,
        is_show_view_count: true,
        is_enable_engagement_tools: true,
        is_loop_video: false,
        is_show_social_interaction_data: false,
        community_ids: [],
        community_loop_ids: [],
        feed_display_pref: "default",
      },
      __v: 0,
    },
    {
      _id: "67c17f9fe0ac202848d7ac5d",
      name: "Blog Embed",
      style: "feed",
      type: "brand_feed",
      brand_id: 2260,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        enable_redirection_tools: {
          community: false,
          group: false,
          user: false,
        },
        links: {
          is_show_links: false,
          position: "overlay",
        },
        carousel_style: "default",
        autoplay: true,
        heading: "Insider Info",
        sub_heading: "Discover what's popular in your community",
        is_floating_view: true,
        is_expanded_view: false,
        is_show_username: false,
        is_show_view_count: true,
        is_enable_engagement_tools: true,
        show_side_panel: false,
        show_join_community_button: false,
        show_community_share_button: false,
        is_enable_redirection: false,
        is_loop_video: false,
        is_show_social_interaction_data: false,
        community_ids: [],
        community_loop_ids: [],
        feed_display_pref: "default",
      },
      __v: 0,
    },
    {
      _id: "67c17f9fe0ac202848d7ac5c",
      name: "Home/Search Embed",
      style: "carousel",
      type: "brand_feed",
      brand_id: 2260,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        cta_button: {
          text: "Explore More",
          url: "https://google.com",
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        links: {
          is_show_links: true,
          position: "outside",
        },
        carousel_style: "default",
        autoplay: true,
        heading: "Specials",
        sub_heading: "Discover what's popular in your community",
        is_carousel_icon: false,
        is_floating_view: false,
        is_show_username: true,
        is_show_view_count: true,
        is_enable_engagement_tools: true,
        is_loop_video: false,
        is_show_social_interaction_data: true,
        community_ids: [],
        community_loop_ids: [],
        feed_display_pref: "default",
      },
      __v: 0,
    },
    {
      _id: "67c17f9fe0ac202848d7ac60",
      name: "PDP Embed",
      style: "carousel",
      type: "brand_feed",
      brand_id: 2260,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        links: {
          is_show_links: true,
          position: "overlay",
        },
        carousel_style: "default",
        autoplay: true,
        heading: "Reviews for you",
        sub_heading: "Discover what's popular in your community",
        is_carousel_icon: false,
        is_floating_view: false,
        is_show_username: false,
        is_show_view_count: true,
        is_enable_engagement_tools: true,
        is_loop_video: false,
        is_show_social_interaction_data: false,
        community_ids: [],
        community_loop_ids: [],
        feed_display_pref: "default",
      },
      __v: 0,
    },
    {
      _id: "67c17f9fe0ac202848d7ac5e",
      name: "Home/Search Embed1",
      style: "feed",
      type: "brand_feed",
      brand_id: 2260,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        enable_redirection_tools: {
          community: false,
          group: false,
          user: false,
        },
        links: {
          is_show_links: false,
          position: "overlay",
        },
        carousel_style: "default",
        autoplay: true,
        is_floating_view: false,
        is_expanded_view: false,
        is_show_username: false,
        is_show_view_count: true,
        is_enable_engagement_tools: true,
        show_side_panel: false,
        show_join_community_button: false,
        show_community_share_button: false,
        is_enable_redirection: false,
        is_loop_video: false,
        is_show_social_interaction_data: false,
        community_ids: [],
        community_loop_ids: [],
        feed_display_pref: "default",
      },
      __v: 0,
    },
    {
      _id: "67c17f9fe0ac202848d7ac61",
      name: "Home/Blog Embed",
      style: "carousel",
      type: "brand_feed",
      brand_id: 2260,
      is_default: true,
      customization: {
        dimensions: {
          width: 800,
          height: 600,
        },
        cta_button: {
          text: "",
          url: "",
          color: "#023F9A",
          text_color: "#023F9A",
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        enable_redirection_tools: {
          community: true,
          group: true,
          user: true,
        },
        links: {
          is_show_links: true,
          position: "overlay",
        },
        carousel_style: "default",
        autoplay: true,
        heading: "",
        heading_text_color: "#212529",
        sub_heading: "",
        sub_heading_text_color: "#6C757D",
        is_carousel_icon: false,
        is_floating_view: false,
        is_show_username: false,
        is_show_view_count: true,
        is_enable_engagement_tools: true,
        show_side_panel: true,
        show_join_community_button: true,
        show_community_share_button: true,
        is_enable_redirection: true,
        is_loop_video: false,
        is_show_social_interaction_data: false,
        community_ids: [],
        is_popup_view: false,
        community_loop_ids: [],
        feed_display_pref: "default",
      },
      __v: 0,
      is_live: true,
    },
    {
      _id: "67c17f9fe0ac202848d7ac5f",
      name: "Post-Sales Embed",
      style: "carousel",
      type: "brand_feed",
      brand_id: 2260,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        links: {
          is_show_links: true,
          position: "overlay",
        },
        carousel_style: "default",
        autoplay: false,
        heading: "Reviews for you",
        sub_heading: "See what others are getting",
        is_carousel_icon: false,
        is_floating_view: false,
        is_show_username: false,
        is_show_view_count: false,
        is_enable_engagement_tools: true,
        show_side_panel: true,
        is_loop_video: true,
        is_show_social_interaction_data: false,
        community_ids: [],
        community_loop_ids: [],
        feed_display_pref: "default",
      },
      __v: 0,
    },
    {
      _id: "67c17f9fe0ac202848d7ac62",
      name: "Home/Post Sales Embed",
      style: "standard_wall",
      type: "brand_feed",
      brand_id: 2260,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        enable_redirection_tools: {
          community: true,
          group: true,
          user: true,
        },
        links: {
          is_show_links: true,
        },
        show_navigation: true,
        carousel_style: "default",
        is_enable_engagement_tools: true,
        show_side_panel: true,
        show_join_community_button: true,
        show_community_share_button: true,
        is_enable_redirection: true,
        is_loop_video: true,
        community_ids: [],
        community_loop_ids: [],
        feed_display_pref: "default",
      },
      __v: 0,
      is_live: true,
    },
  ],
  slogan: {
    text: "Create your own brand",
    image:
      "https://media.qa.begenuin.com/uploads/brands/slogan_image/1f49226365001400.png",
    font: {
      _id: "65f04ccf322929c13ba07082",
      weight: "normal",
      style: "normal",
    },
  },
  environment: "PROD",
};

const preview: Preview = {
  decorators: [
    (Story) => {
      const parsedColor = parseBrandColors(brandDetails.brand_colors);
      return (
        <AuthProvider
          user={{
            isAvatar: false,
            id: "b6aebf66-db37-48bf-8fac-bda06eb81914",
            phoneNumber: "916354665097",
            nickname: "ycombinator",
            image:
              "https://media.qa.begenuin.com/uploads/profile_images/1741280553604_croppedImage_1741280519374.png",
            email: "himanshu@begenuin.com",
            name: "ycombinator",
            accessToken:
              "eyJraWQiOiJkLTE3NDk4MDgyMzY3ODMiLCJ0eXAiOiJKV1QiLCJ2ZXJzaW9uIjoiNSIsImFsZyI6IlJTMjU2In0.eyJpYXQiOjE3NDk4MjQ0MjksImV4cCI6MTc1MTAzNDAyOCwic3ViIjoiYjJmOTcxNTItOGQxYi00ZmM5LTkwNzItMzdiMjI5YWFmYWYxIiwidElkIjoicHVibGljIiwicnN1YiI6ImIyZjk3MTUyLThkMWItNGZjOS05MDcyLTM3YjIyOWFhZmFmMSIsInNlc3Npb25IYW5kbGUiOiJiZmQwZDFjYy03ZmUxLTQzNmUtODI1My01NGQxZDQzMGUzNWMiLCJyZWZyZXNoVG9rZW5IYXNoMSI6IjQwZGI1ZTU2ZjYxMjIxMGVkM2E1NzA3YjlkM2RiYjdkNGM0MDBhMzFjOTU4N2RlMWMwODVkZDc2YWRmNjM3NDgiLCJwYXJlbnRSZWZyZXNoVG9rZW5IYXNoMSI6bnVsbCwiYW50aUNzcmZUb2tlbiI6bnVsbCwiaXNzIjoiaHR0cHM6Ly9ub2RlanMucWEuYmVnZW51aW4uY29tL2FwaS92NC9hdXRoIiwic3Qtcm9sZSI6eyJ2IjpbXSwidCI6MTc0OTgyNDQyODY5NX0sInN0LXBlcm0iOnsidiI6W10sInQiOjE3NDk4MjQ0Mjg2OTZ9LCJnZW51aW4iOnsidXNlcl9pZCI6ImI2YWViZjY2LWRiMzctNDhiZi04ZmFjLWJkYTA2ZWI4MTkxNCIsImxvZ2luX3NvdXJjZSI6MywiZGV2aWNlX3R5cGUiOiJ3ZWIiLCJicmFuZF9pZCI6MjI2MH19.Ae-HpYiG2SK40AfoAQfePmglrxxLA--XYl_anVTVQhnV1nW2WBuz4bD51pJPr2JABds4J4Qna2T3V296gy8PBt8Ose88bzFoccRBRU1S77LKe4_Ojqqbe4cRLc_M5t0UkpCFAnvQKd9egre9XIduT2x3GyCC7Lb8_5gqSLfVNkrpp0wz3eB31QRkvKMKKBE8f5SPBlyUwHwnOFFBFfEMdeRD8T9VRUlEZaWdYUtPiV4vwnGM4kV3lfu56_mP0Qg7b52MZZUVoZdqPyMXNcqzudTHBnkG0cQSe_tcXQ5zUUEfxZZ9h_-VZljX0RYiBTD6aUzpQwenPmiewjF8atSuRg",
            ksCbRequestStatus: 1,
            isBrandSystemUser: true,
            brandId: 2260,
            brandSlug: "ycombinator",
            hasTopics: true,
            refreshToken:
              "d/4WndBLTrRcowEqOKGsU7NQwDTIcGjNOHuX6g2rt1AdhMdMDNF6uChX4kI/bZPAyC+7IY7NzSJNNCL92Drk7o1rLhTJtR4INhwKUiwQsXIstlXV9CqtWEQsa7/gQCLHUS0oAo93jVdA9dIbRm6vb25UAZzyKOF6Y5nIOpTykMEgQZUgvCZgRoH0VVbOwBd9vP0EIKfCCJni9vr+Aw8g+Ckz5yLqQBpDmKlFeRxOHMlhBSLuLMlWogf8HaD0F4RcGFWCu1B9eWRAMrGls7/V.7913f90c5bc557d41f084b6733356e6a25ab3bcae9cb56674c58d716dac9ef25.V2",
            usernameSet: true,
          }}
        >
          <BaseContextProvider brandDetails={brandDetails}>
            <ReactQueryClientProvider>
              <main style={{ ...parsedColor }}>
                <Story />
                <Toaster />
              </main>
            </ReactQueryClientProvider>
          </BaseContextProvider>
        </AuthProvider>
      );
    },
  ],
  parameters: {
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },
    },
  },
};

export default preview;
