import { EmbedDataType } from "../src/context/embed/embed.types";

export const testBrandDetails = {
  brand_id: 1429,
  type: 3,
  is_claimed: false,
  website: "https://www.bmw.in/en/index.html",
  name: "BMW",
  status: 1,
  subdomain: "ehlmoceg",
  logo: "https://media.qa.begenuin.com/uploads/brands/logo/brandProfileLogo_1745490652674.png",
  created_at: 1745489900,
  integrations: {
    sdk: {
      web: {
        enable: true,
        hide_navbar: true,
      },
      android: {
        enable: false,
        playstore_link:
          "https://play.google.com/store/apps/details?id=de.bmw.connected.mobile20.row&hl=en_IN",
      },
      ios: {
        enable: true,
        appstore_link: "https://apps.apple.com/us/app/my-bmw/id1519457734",
      },
    },
    white_label: {
      enable: true,
      allowed_domains: [],
      test_allowed_domains: [],
    },
  },
  brand_colors: {
    primary: {
      primary: "#0166b1",
      primary_100: "#e6f0f7",
      primary_200: "#cce0ef",
      primary_300: "#80b3d8",
      primary_400: "#4d94c8",
      primary_600: "#01477c",
      primary_700: "#013359",
    },
    secondary: {
      secondary: "#000000",
      secondary_300: "#666666",
      secondary_400: "#333333",
      secondary_600: "#000000",
    },
    tertiary: {
      tertiary: "#acacac",
      tertiary_100: "#fbfbfb",
      tertiary_200: "#f7f7f7",
      tertiary_300: "#dedede",
      tertiary_400: "#c5c5c5",
    },
  },
  brand_web_logo:
    "https://media.qa.begenuin.com/uploads/brands/web_logo/brandWebLogo_1745490382966.png",
  favicon:
    "https://media.qa.begenuin.com/uploads/brands/favicon/brandFavicon_1745490670049.png",
  is_wallet_enabled: false,
  global_reward_point_configs: {
    view: 1,
    spark: 1,
    comments: 1,
    repost: 1,
  },
  social_login: {
    google: true,
    apple: true,
    brand: false,
    brand_sso_id: null,
  },
  web_cta: "both",
  is_interruption_disabled: false,
  show_become_creator: true,
  api_key: "99ca94df0d557bd899758a108781a71aa608a2da6d6edf6a",
  reactions: {
    type: "like",
    title: "react",
    suffix: "to",
    tooltip: "I like this!",
    keys: {
      comment_selected: {
        png: "https://media.qa.begenuin.com/webapp_assets/reactions/like/comment_selected.png",
        svg: "https://media.qa.begenuin.com/webapp_assets/reactions/like/comment_selected.svg",
      },
      comment_unselected: {
        png: "https://media.qa.begenuin.com/webapp_assets/reactions/like/comment_unselected.png",
        svg: "https://media.qa.begenuin.com/webapp_assets/reactions/like/comment_unselected.svg",
      },
      feed_animate: {
        png: "https://media.qa.begenuin.com/webapp_assets/reactions/like/feed_animate.png",
        svg: "https://media.qa.begenuin.com/webapp_assets/reactions/like/feed_animate.svg",
      },
      feed_selected: {
        png: "https://media.qa.begenuin.com/webapp_assets/reactions/like/feed_selected.png",
        svg: "https://media.qa.begenuin.com/webapp_assets/reactions/like/feed_selected.svg",
      },
      feed_unselected: {
        png: "https://media.qa.begenuin.com/webapp_assets/reactions/like/feed_unselected.png",
        svg: "https://media.qa.begenuin.com/webapp_assets/reactions/like/feed_unselected.svg",
      },
    },
  },
  privacy_policy:
    "https://www.bmw.in/en/footer/metanavigation/privacy-policy.html",
  industry_type: 1,
  terms_and_condition:
    "https://www.bmw.in/en/footer/metanavigation/legal-disclaimer-imprint.html",
  mobile_configs: {
    video_autoplay: {
      type: 1,
      auto_play_after: 5,
      is_start_with_sound: false,
    },
    feed_video_play: {
      type: 1,
      repeat_video: 0,
      swipe_after: 0,
    },
    linkout_delay: {
      type: 1,
      appear_after: 10,
    },
    login_signup_popup: {
      enable: true,
      popup_after: 5,
    },
    interest_selection_popup: {
      enable: true,
      popup_after: 5,
    },
    username_popup: {
      enable: true,
      popup_after: 5,
    },
    complete_profile_popup: {
      enable: true,
      popup_after: 5,
    },
    idle_time_interruption: {
      enable: true,
      popup_after: 60,
    },
    playback_speed_enabled: true,
    video_aspect_ratio: "9:16",
    tap_behavior: 1,
    share_transcript_enabled: false,
    gesture_guidance: true,
    is_start_with_sound: true,
  },
  web_configs: {
    share_transcript_enabled: false,
    playback_speed_enabled: true,
    video_aspect_ratio: "9:16",
    video_autoplay: {
      type: 1,
      auto_play_after: 5,
      is_start_with_sound: false,
    },
    feed_video_play: {
      type: 1,
      repeat_video: 0,
      swipe_after: 5,
    },
    tap_behavior: 3,
    linkout_delay: {
      type: 2,
      appear_after: 10,
    },
    login_signup_popup: {
      enable: true,
      popup_after: 5,
    },
    get_app_popup: {
      enable: true,
      popup_after: 5,
    },
    interest_selection_popup: {
      enable: true,
      popup_after: 5,
    },
    username_popup: {
      enable: true,
      popup_after: 5,
    },
    complete_profile_popup: {
      enable: true,
      popup_after: 5,
    },
    idle_time_interruption: {
      enable: true,
      popup_after: 60,
    },
    gesture_guidance: true,
    is_start_with_sound: false,
  },
  sitemap_configs: {
    asset_links_config: [],
  },
  white_label_url: "https://ehlmoceg.begenuin.com",
  protected_content: true,
  pin_limit: {
    loop: 2,
    loop_videos: 2,
  },
  ad_configs: {
    feed_stream: false,
    in_video_stream: false,
  },
  comment_type: {
    text: true,
    video: true,
    audio: true,
  },
  camera_enabled: true,
  default_embeds: [
    {
      embed_layout: "default",
      _id: "680a127bf82af8fb0cb20556",
      name: "Home/Search Embed",
      style: "carousel",
      type: "brand_feed",
      brand_id: 2910,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        cta_button: {
          text: "Explore More",
          url: "https://google.com",
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        links: {
          is_show_links: true,
          position: "outside",
        },
        show_navigation: false,
        carousel_style: "default",
        autoplay: true,
        feed_display_pref: "default",
        heading: "Specials",
        sub_heading: "Discover what's popular in your community",
        is_carousel_icon: false,
        is_floating_view: false,
        is_expanded_view: false,
        is_show_username: true,
        is_show_view_count: true,
        is_enable_engagement_tools: true,
        show_side_panel: false,
        show_join_community_button: false,
        show_community_share_button: false,
        is_enable_redirection: false,
        is_loop_video: false,
        is_show_social_interaction_data: true,
        community_ids: [],
        is_popup_view: false,
        video_crop: true,
        community_loop_ids: [],
      },
    },
    {
      embed_layout: "default",
      _id: "680a127bf82af8fb0cb20557",
      name: "Blog Embed",
      style: "feed",
      type: "brand_feed",
      brand_id: 2910,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        enable_redirection_tools: {
          community: false,
          group: false,
          user: false,
        },
        links: {
          is_show_links: false,
          position: "overlay",
        },
        show_navigation: false,
        carousel_style: "default",
        autoplay: true,
        feed_display_pref: "default",
        heading: "Insider Info",
        sub_heading: "Discover what's popular in your community",
        is_carousel_icon: false,
        is_floating_view: false,
        is_expanded_view: false,
        is_show_username: false,
        is_show_view_count: true,
        is_enable_engagement_tools: true,
        show_side_panel: false,
        show_join_community_button: false,
        show_community_share_button: false,
        is_enable_redirection: false,
        is_loop_video: false,
        is_show_social_interaction_data: false,
        community_ids: [],
        is_popup_view: false,
        video_crop: true,
        community_loop_ids: [],
      },
    },
    {
      embed_layout: "default",
      _id: "680a127bf82af8fb0cb20558",
      name: "Home/Search Embed1",
      style: "feed",
      type: "brand_feed",
      brand_id: 2910,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        enable_redirection_tools: {
          community: false,
          group: false,
          user: false,
        },
        links: {
          is_show_links: false,
          position: "overlay",
        },
        show_navigation: false,
        carousel_style: "default",
        autoplay: true,
        feed_display_pref: "default",
        is_carousel_icon: false,
        is_floating_view: false,
        is_expanded_view: false,
        is_show_username: false,
        is_show_view_count: true,
        is_enable_engagement_tools: true,
        show_side_panel: false,
        show_join_community_button: false,
        show_community_share_button: false,
        is_enable_redirection: false,
        is_loop_video: false,
        is_show_social_interaction_data: false,
        community_ids: [],
        is_popup_view: false,
        video_crop: true,
        community_loop_ids: [],
      },
    },
    {
      embed_layout: "default",
      _id: "680a127bf82af8fb0cb20559",
      name: "Post-Sales Embed",
      style: "carousel",
      type: "brand_feed",
      brand_id: 2910,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        links: {
          is_show_links: true,
          position: "overlay",
        },
        show_navigation: false,
        carousel_style: "default",
        autoplay: false,
        feed_display_pref: "default",
        heading: "Reviews for you",
        sub_heading: "See what others are getting",
        is_carousel_icon: false,
        is_floating_view: false,
        is_expanded_view: false,
        is_show_username: false,
        is_show_view_count: false,
        is_enable_engagement_tools: true,
        show_side_panel: true,
        show_join_community_button: false,
        show_community_share_button: false,
        is_enable_redirection: false,
        is_loop_video: true,
        is_show_social_interaction_data: false,
        community_ids: [],
        is_popup_view: false,
        video_crop: true,
        community_loop_ids: [],
      },
    },
    {
      embed_layout: "default",
      _id: "680a127bf82af8fb0cb2055a",
      name: "PDP Embed",
      style: "carousel",
      type: "brand_feed",
      brand_id: 2910,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        links: {
          is_show_links: true,
          position: "overlay",
        },
        show_navigation: false,
        carousel_style: "default",
        autoplay: true,
        feed_display_pref: "default",
        heading: "Reviews for you",
        sub_heading: "Discover what's popular in your community",
        is_carousel_icon: false,
        is_floating_view: false,
        is_expanded_view: false,
        is_show_username: false,
        is_show_view_count: true,
        is_enable_engagement_tools: true,
        show_side_panel: false,
        show_join_community_button: false,
        show_community_share_button: false,
        is_enable_redirection: false,
        is_loop_video: false,
        is_show_social_interaction_data: false,
        community_ids: [],
        is_popup_view: false,
        video_crop: true,
        community_loop_ids: [],
      },
    },
    {
      embed_layout: "default",
      _id: "680a127bf82af8fb0cb2055b",
      name: "Home/Blog Embed",
      style: "carousel",
      type: "brand_feed",
      brand_id: 2910,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        links: {
          is_show_links: true,
          position: "overlay",
        },
        show_navigation: false,
        carousel_style: "default",
        autoplay: true,
        feed_display_pref: "default",
        is_carousel_icon: false,
        is_floating_view: true,
        is_expanded_view: false,
        is_show_username: false,
        is_show_view_count: true,
        is_enable_engagement_tools: true,
        show_side_panel: false,
        show_join_community_button: false,
        show_community_share_button: false,
        is_enable_redirection: false,
        is_loop_video: false,
        is_show_social_interaction_data: false,
        community_ids: [],
        is_popup_view: false,
        video_crop: true,
        community_loop_ids: [],
      },
    },
    {
      embed_layout: "default",
      _id: "680a127bf82af8fb0cb2055c",
      name: "Home/Post Sales Embed",
      style: "standard_wall",
      type: "brand_feed",
      brand_id: 2910,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        links: {
          is_show_links: true,
          position: "overlay",
        },
        show_navigation: true,
        carousel_style: "default",
        autoplay: false,
        feed_display_pref: "default",
        is_carousel_icon: false,
        is_floating_view: false,
        is_expanded_view: false,
        is_show_username: false,
        is_show_view_count: false,
        is_enable_engagement_tools: true,
        show_side_panel: false,
        show_join_community_button: false,
        show_community_share_button: false,
        is_enable_redirection: false,
        is_loop_video: true,
        is_show_social_interaction_data: false,
        community_ids: [],
        is_popup_view: false,
        video_crop: true,
        community_loop_ids: [],
      },
    },
  ],
  slogan: {
    text: "Ultimate Driving Machine",
    image:
      "https://media.qa.begenuin.com/uploads/brands/slogan_image/1f397b1697801403.png",
    font: {
      _id: "65f04ccf322929c13ba07083",
      style: "normal",
      weight: "normal",
    },
  },
  environment: "PROD",
};

export const testEmbedData: EmbedDataType = {
  embed_layout: "default",
  _id: "68ac0f803ba4058d9ec9711f",
  name: "Carousel",
  style: "carousel",
  placement_id: "68a70d3177806502ba2a9a57",
  style_id: "68a70d3177806502ba2a9a58",
  type: "brand_feed",
  brand_id: 2910,
  customization: {
    dimensions: {
      width: 800,
      height: 600,
    },
    cta_button: {
      color: "#023F9A",
      text_color: "#FFFFFF",
      text: "",
      url: "",
    },
    enable_engagement_tools: {
      repost: true,
      spark: true,
      comment: true,
      share: true,
    },
    enable_redirection_tools: {
      community: true,
      group: true,
      user: true,
    },
    // to change
    links: {
      is_show_links: false,
      position: "overlay",
    },

    show_navigation: false,
    carousel_style: "default",

    // key is different
    autoplay: false,

    // key is missing
    feed_display_pref: "default",

    heading_text_color: "#212529",
    sub_heading_text_color: "#6C757D",
    is_carousel_icon: false,
    is_floating_view: false,
    is_expanded_view: false,
    is_show_username: false,
    is_show_view_count: false,
    is_enable_engagement_tools: true,

    // missing
    show_side_panel: true,

    show_join_community_button: true,
    show_community_share_button: true,
    is_enable_redirection: true,
    is_loop_video: false,
    is_show_social_interaction_data: false,
    community_ids: [],

    // missing
    is_popup_view: true,
    video_crop: true,

    community_loop_ids: [],
  },

  // diff key
  card_layout_id: 6,
  video_layout_id: 5,
};
