import { EmbedDataType } from "../src/context/embed/embed.types";

export const testBrandDetails = {
  brand_id: 2922,
  type: 1,
  is_claimed: true,
  website: "https://shop.lululemon.com/",
  name: "lululemon",
  status: 1,
  subdomain: "xcqajpyh",
  logo: "https://media.qa.begenuin.com/uploads/brands/logo/brandProfileLogo_1745646632621.png",
  created_at: 1745646500077,
  integrations: {
    sdk: {
      web: {
        enable: true,
        hide_navbar: true,
      },
      android: {
        enable: true,
        playstore_link:
          "https://play.google.com/store/apps/details?id=co.mirror.android&hl=en",
      },
      ios: {
        enable: true,
        appstore_link: "https://apps.apple.com/us/app/lululemon/id920098546",
      },
    },
    white_label: {
      enable: true,
      allowed_domains: [],
      test_allowed_domains: [],
    },
  },
  brand_colors: {
    primary: {
      primary_100: "#fae6ea",
      primary_200: "#f5cdd5",
      primary_300: "#e78295",
      primary_400: "#dd506b",
      primary: "#cf052b",
      primary_600: "#91041e",
      primary_700: "#680316",
    },
    secondary: {
      secondary_300: "#a0a0a0",
      secondary_400: "#818181",
      secondary: "#616161",
      secondary_600: "#4e4e4e",
    },
    tertiary: {
      tertiary: "#000000",
      tertiary_400: "#4d4d4d",
      tertiary_300: "#999999",
      tertiary_200: "#e6e6e6",
      tertiary_100: "#f2f2f2",
    },
  },
  brand_web_logo:
    "https://media.qa.begenuin.com/uploads/brands/web_logo/brandWebLogo_1745646695319.png",
  favicon:
    "https://media.qa.begenuin.com/uploads/brands/favicon/brandFavicon_1745646653918.png",
  is_wallet_enabled: false,
  global_reward_point_configs: {
    view: 1,
    spark: 1,
    comments: 1,
    repost: 1,
  },
  social_login: {
    google: true,
    apple: true,
    brand: false,
    brand_sso_id: null,
  },
  web_cta: "app",
  is_interruption_disabled: false,
  show_become_creator: true,
  api_key: "ca5a1ee517389afe3604c47955e8b37d8a650d7c9575fa20",
  reactions: {
    type: "like",
    title: "react",
    suffix: "to",
    keys: {
      comment_selected: {
        png: "https://media.qa.begenuin.com/webapp_assets/reactions/like/comment_selected.png",
        svg: "https://media.qa.begenuin.com/webapp_assets/reactions/like/comment_selected.svg",
      },
      comment_unselected: {
        png: "https://media.qa.begenuin.com/webapp_assets/reactions/like/comment_unselected.png",
        svg: "https://media.qa.begenuin.com/webapp_assets/reactions/like/comment_unselected.svg",
      },
      feed_animate: {
        png: "https://media.qa.begenuin.com/webapp_assets/reactions/like/feed_animate.png",
        svg: "https://media.qa.begenuin.com/webapp_assets/reactions/like/feed_animate.svg",
      },
      feed_selected: {
        png: "https://media.qa.begenuin.com/webapp_assets/reactions/like/feed_selected.png",
        svg: "https://media.qa.begenuin.com/webapp_assets/reactions/like/feed_selected.svg",
      },
      feed_unselected: {
        png: "https://media.qa.begenuin.com/webapp_assets/reactions/like/feed_unselected.png",
        svg: "https://media.qa.begenuin.com/webapp_assets/reactions/like/feed_unselected.svg",
      },
    },
    tooltip: "I like this!",
  },
  privacy_policy: null,
  industry_type: 7,
  terms_and_condition: null,
  mobile_configs: {
    video_autoplay: {
      type: 1,
      auto_play_after: 5,
    },
    feed_video_play: {
      type: 1,
      repeat_video: 0,
      swipe_after: 5,
    },
    linkout_delay: {
      type: 1,
      appear_after: 10,
    },
    login_signup_popup: {
      enable: true,
      popup_after: 5,
    },
    interest_selection_popup: {
      enable: true,
      popup_after: 5,
    },
    username_popup: {
      enable: true,
      popup_after: 5,
    },
    complete_profile_popup: {
      enable: true,
      popup_after: 5,
    },
    idle_time_interruption: {
      enable: true,
      popup_after: 60,
    },
    playback_speed_enabled: false,
    video_aspect_ratio: "9:16",
    tap_behavior: 1,
    share_transcript_enabled: false,
    gesture_guidance: true,
    is_start_with_sound: true,
  },
  web_configs: {
    video_autoplay: {
      type: 1,
      auto_play_after: 5,
    },
    feed_video_play: {
      type: 1,
      repeat_video: 0,
      swipe_after: 5,
    },
    linkout_delay: {
      type: 1,
      appear_after: 10,
    },
    login_signup_popup: {
      enable: true,
      popup_after: 5,
    },
    get_app_popup: {
      enable: true,
      popup_after: 5,
    },
    interest_selection_popup: {
      enable: true,
      popup_after: 5,
    },
    username_popup: {
      enable: true,
      popup_after: 5,
    },
    complete_profile_popup: {
      enable: true,
      popup_after: 5,
    },
    idle_time_interruption: {
      enable: true,
      popup_after: 60,
    },
    share_transcript_enabled: false,
    playback_speed_enabled: true,
    video_aspect_ratio: "9:16",
    tap_behavior: 3,
    gesture_guidance: true,
    is_start_with_sound: false,
  },
  sitemap_configs: {
    robots_config: [],
    asset_links_config: [],
  },
  white_label_url: "https://xcqajpyh.qa.begenuin.com",
  protected_content: true,
  pin_limit: {
    loop: 2,
    loop_videos: 2,
  },
  ad_configs: {
    feed_stream: false,
    in_video_stream: false,
  },
  comment_type: {
    text: true,
    video: true,
    audio: true,
  },
  camera_enabled: true,
  card_layout_id: 2,
  video_layout_id: 2,
  default_embeds: [
    {
      embed_layout: "default",
      _id: "680c753b8dafc1f24a294098",
      name: "Blog Embed",
      style: "feed",
      type: "brand_feed",
      brand_id: 2922,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        enable_redirection_tools: {
          community: false,
          group: false,
          user: false,
        },
        links: {
          is_show_links: false,
          position: "overlay",
        },
        carousel_style: "default",
        autoplay: true,
        feed_display_pref: "default",
        heading: "Insider Info",
        sub_heading: "Discover what's popular in your community",
        is_floating_view: true,
        is_expanded_view: false,
        is_show_username: false,
        is_show_view_count: true,
        is_enable_engagement_tools: true,
        show_side_panel: false,
        show_join_community_button: false,
        show_community_share_button: false,
        is_enable_redirection: false,
        is_loop_video: false,
        is_show_social_interaction_data: false,
        community_ids: [],
        community_loop_ids: [],
        video_crop: true,
      },
      __v: 0,
    },
    {
      embed_layout: "default",
      _id: "680c753b8dafc1f24a294099",
      name: "Home/Search Embed1",
      style: "feed",
      type: "brand_feed",
      brand_id: 2922,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        enable_redirection_tools: {
          community: false,
          group: false,
          user: false,
        },
        links: {
          is_show_links: false,
          position: "overlay",
        },
        carousel_style: "default",
        autoplay: true,
        feed_display_pref: "default",
        is_floating_view: false,
        is_expanded_view: false,
        is_show_username: false,
        is_show_view_count: true,
        is_enable_engagement_tools: true,
        show_side_panel: false,
        show_join_community_button: false,
        show_community_share_button: false,
        is_enable_redirection: false,
        is_loop_video: false,
        is_show_social_interaction_data: false,
        community_ids: [],
        community_loop_ids: [],
        video_crop: true,
      },
      __v: 0,
    },
    {
      embed_layout: "default",
      _id: "680c753b8dafc1f24a29409a",
      name: "Post-Sales Embed",
      style: "carousel",
      type: "brand_feed",
      brand_id: 2922,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        links: {
          is_show_links: true,
          position: "overlay",
        },
        carousel_style: "default",
        autoplay: false,
        feed_display_pref: "default",
        heading: "Reviews for you",
        sub_heading: "See what others are getting",
        is_carousel_icon: false,
        is_floating_view: false,
        is_show_username: false,
        is_show_view_count: false,
        is_enable_engagement_tools: true,
        show_side_panel: true,
        is_loop_video: true,
        is_show_social_interaction_data: false,
        community_ids: [],
        community_loop_ids: [],
        video_crop: true,
      },
      __v: 0,
    },
    {
      embed_layout: "default",
      _id: "680c753b8dafc1f24a29409b",
      name: "PDP Embed",
      style: "carousel",
      type: "brand_feed",
      brand_id: 2922,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        links: {
          is_show_links: true,
          position: "overlay",
        },
        carousel_style: "default",
        autoplay: true,
        feed_display_pref: "default",
        heading: "Reviews for you",
        sub_heading: "Discover what's popular in your community",
        is_carousel_icon: false,
        is_floating_view: false,
        is_show_username: false,
        is_show_view_count: true,
        is_enable_engagement_tools: true,
        is_loop_video: false,
        is_show_social_interaction_data: false,
        community_ids: [],
        community_loop_ids: [],
        video_crop: true,
      },
      __v: 0,
    },
    {
      embed_layout: "default",
      _id: "680c753b8dafc1f24a294097",
      name: "Home/Search Embed",
      style: "carousel",
      type: "brand_feed",
      brand_id: 2922,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        cta_button: {
          text: "Explore More",
          url: "https://google.com",
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        links: {
          is_show_links: true,
          position: "outside",
        },
        carousel_style: "default",
        autoplay: true,
        feed_display_pref: "default",
        heading: "Specials",
        sub_heading: "Discover what's popular in your community",
        is_carousel_icon: false,
        is_floating_view: false,
        is_show_username: true,
        is_show_view_count: true,
        is_enable_engagement_tools: true,
        is_loop_video: false,
        is_show_social_interaction_data: true,
        community_ids: [],
        community_loop_ids: [],
        video_crop: true,
      },
      __v: 0,
    },
    {
      embed_layout: "default",
      _id: "680c753b8dafc1f24a29409c",
      name: "Home/Blog Embed",
      style: "carousel",
      type: "brand_feed",
      brand_id: 2922,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        links: {
          is_show_links: true,
          position: "overlay",
        },
        carousel_style: "default",
        autoplay: true,
        feed_display_pref: "default",
        is_carousel_icon: false,
        is_floating_view: true,
        is_show_username: false,
        is_show_view_count: true,
        is_enable_engagement_tools: true,
        is_loop_video: false,
        is_show_social_interaction_data: false,
        community_ids: [],
        community_loop_ids: [],
        video_crop: true,
      },
      __v: 0,
    },
    {
      embed_layout: "default",
      _id: "680c753b8dafc1f24a29409d",
      name: "Home/Post Sales Embed",
      style: "standard_wall",
      type: "brand_feed",
      brand_id: 2922,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        links: {
          is_show_links: true,
          position: "overlay",
        },
        show_navigation: true,
        carousel_style: "default",
        autoplay: false,
        feed_display_pref: "default",
        is_carousel_icon: false,
        is_floating_view: false,
        is_show_username: false,
        is_show_view_count: false,
        is_enable_engagement_tools: true,
        is_loop_video: true,
        is_show_social_interaction_data: false,
        community_ids: [],
        community_loop_ids: [],
        video_crop: true,
      },
      __v: 0,
    },
  ],
  slogan: {
    text: "Be all in",
    image:
      "https://media.qa.begenuin.com/uploads/brands/slogan_image/200f3ea537801400.png",
    font: {
      _id: "65f04ccf322929c13ba07083",
      weight: "bolder",
      style: "normal",
    },
  },
  environment: "PROD",
};

export const testEmbedData: EmbedDataType = {
  embed_layout: "default",
  embed_id: "6824304055db06e58e479de4",
  environment: "PROD",
  elementId: "gen-sdk",
  name: "carousel_example",
  style: "carousel" as const,
  type: "brand_feed" as const,
  // startVideoSlug: "Test",
  brand_id: 2922 as number,
  customization: {
    dimensions: {
      width: 800,
      height: 600,
    },
    cta_button: {
      text: "This is button test",
      url: "test.com",
      color: "#023F9A",
      text_color: "#ffffff",
    },
    enable_engagement_tools: {
      repost: true,
      spark: true,
      comment: true,
      share: true,
    },
    enable_redirection_tools: {
      community: true,
      group: true,
      user: true,
    },
    links: {
      is_show_links: true,
      position: "overlay",
    },
    carousel_style: "default",
    autoplay: false,
    feed_display_pref: "default",
    heading: "This is test",
    heading_text_color: "#212529",
    sub_heading: "Hiii",
    sub_heading_text_color: "#6C757D",
    is_carousel_icon: false,
    is_floating_view: true,
    is_show_username: true,
    is_show_view_count: false,
    is_enable_engagement_tools: true,
    show_side_panel: true,
    show_join_community_button: true,
    show_community_share_button: true,
    is_enable_redirection: true,
    is_loop_video: false,
    is_show_social_interaction_data: false,
    community_ids: [],
    is_popup_view: true,
    community_loop_ids: [],
    video_crop: true,
  },
} as any;
