import { EmbedDataType } from "../src/context/embed/embed.types";

export const testBrandDetails = {
  brand_id: 1441,
  type: 1,
  is_claimed: true,
  website: "https://www.walmart.com/",
  name: "Walmart",
  status: 1,
  subdomain: "walmart",
  logo: "https://media.begenuin.com/uploads/brands/logo/brandProfileLogo_1713970089341.png",
  created_at: 1713969597,
  integrations: {
    sdk: {
      web: {
        enable: true,
        hide_navbar: true,
      },
      android: {
        enable: true,
        playstore_link:
          "https://play.google.com/store/apps/details?id=com.walmart.android&hl=en_US&pli=1",
      },
      ios: {
        enable: true,
        appstore_link:
          "https://apps.apple.com/us/app/walmart-shopping-savings/id338137227",
      },
    },
    white_label: {
      enable: true,
      allowed_domains: [],
      test_allowed_domains: [],
    },
  },
  brand_colors: {
    primary: {
      primary: "#0071ce",
      primary_100: "#e6f1fa",
      primary_200: "#cce3f5",
      primary_300: "#80b8e7",
      primary_400: "#4d9cdd",
      primary_600: "#004f90",
      primary_700: "#003967",
    },
    secondary: {
      secondary: "#111111",
      secondary_300: "#707070",
      secondary_400: "#414141",
      secondary_600: "#0e0e0e",
    },
    tertiary: {
      tertiary: "#949494",
      tertiary_100: "#fafafa",
      tertiary_200: "#f4f4f4",
      tertiary_300: "#d4d4d4",
      tertiary_400: "#b4b4b4",
    },
  },
  brand_web_logo:
    "https://media.begenuin.com/uploads/brands/web_logo/brandWebLogo_1718186294261.png",
  favicon:
    "https://media.begenuin.com/uploads/brands/favicon/brandFavicon_1718186294262.png",
  is_wallet_enabled: false,
  global_reward_point_configs: {
    view: 1,
    spark: 1,
    comments: 1,
    repost: 1,
  },
  social_login: {
    google: true,
    apple: true,
    brand: false,
    brand_sso_id: null,
  },
  web_cta: "app",
  is_interruption_disabled: false,
  show_become_creator: false,
  api_key: "8a4c63638d23c36eb19f6d8b7c89f7d784bd281074771a62",
  reactions: {
    type: "like",
    title: "react",
    suffix: "to",
    tooltip: "I like this!",
    keys: {
      comment_selected: {
        png: "https://media.begenuin.com/webapp_assets/reactions/like/comment_selected.png",
        svg: "https://media.begenuin.com/webapp_assets/reactions/like/comment_selected.svg",
      },
      comment_unselected: {
        png: "https://media.begenuin.com/webapp_assets/reactions/like/comment_unselected.png",
        svg: "https://media.begenuin.com/webapp_assets/reactions/like/comment_unselected.svg",
      },
      feed_animate: {
        png: "https://media.begenuin.com/webapp_assets/reactions/like/feed_animate.png",
        svg: "https://media.begenuin.com/webapp_assets/reactions/like/feed_animate.svg",
      },
      feed_selected: {
        png: "https://media.begenuin.com/webapp_assets/reactions/like/feed_selected.png",
        svg: "https://media.begenuin.com/webapp_assets/reactions/like/feed_selected.svg",
      },
      feed_unselected: {
        png: "https://media.begenuin.com/webapp_assets/reactions/like/feed_unselected.png",
        svg: "https://media.begenuin.com/webapp_assets/reactions/like/feed_unselected.svg",
      },
    },
  },
  privacy_policy: null,
  industry_type: 7,
  terms_and_condition: null,
  mobile_configs: {
    video_autoplay: {
      type: 1,
      auto_play_after: 5,
      is_start_with_sound: false,
    },
    feed_video_play: {
      type: 1,
      repeat_video: 0,
      swipe_after: 5,
    },
    linkout_delay: {
      type: 2,
      appear_after: 1,
    },
    login_signup_popup: {
      enable: true,
      popup_after: 5,
    },
    interest_selection_popup: {
      enable: true,
      popup_after: 5,
    },
    username_popup: {
      enable: true,
      popup_after: 5,
    },
    complete_profile_popup: {
      enable: true,
      popup_after: 5,
    },
    idle_time_interruption: {
      enable: true,
      popup_after: 60,
    },
    playback_speed_enabled: true,
    video_aspect_ratio: "9:16",
    tap_behavior: 1,
    share_transcript_enabled: false,
    gesture_guidance: true,
    is_start_with_sound: true,
  },
  web_configs: {
    share_transcript_enabled: false,
    playback_speed_enabled: true,
    video_aspect_ratio: "9:16",
    video_autoplay: {
      type: 1,
      auto_play_after: 5,
      is_start_with_sound: false,
    },
    feed_video_play: {
      type: 1,
      repeat_video: 0,
      swipe_after: 5,
    },
    tap_behavior: 2,
    linkout_delay: {
      type: 2,
      appear_after: 10,
    },
    login_signup_popup: {
      enable: true,
      popup_after: 5,
    },
    get_app_popup: {
      enable: true,
      popup_after: 5,
    },
    interest_selection_popup: {
      enable: true,
      popup_after: 5,
    },
    username_popup: {
      enable: true,
      popup_after: 5,
    },
    complete_profile_popup: {
      enable: true,
      popup_after: 5,
    },
    idle_time_interruption: {
      enable: true,
      popup_after: 60,
    },
    gesture_guidance: true,
    is_start_with_sound: false,
  },
  sitemap_configs: {
    asset_links_config: [],
  },
  white_label_url: "https://walmart.begenuin.com",
  protected_content: false,
  pin_limit: {
    loop: 2,
    loop_videos: 2,
  },
  ad_configs: {
    feed_stream: false,
    in_video_stream: false,
  },
  comment_type: {
    text: true,
    video: true,
    audio: true,
  },
  fonts_config: {
    size: 0,
    fonts: {
      bold: "https://media.begenuin.com/webapp_assets/fonts/walmart/EverydaySansBold.otf",
      bold_italic:
        "https://media.begenuin.com/webapp_assets/fonts/walmart/EverydaySansBoldItalic.otf",
      demi_bold:
        "https://media.begenuin.com/webapp_assets/fonts/walmart/EverydaySansMedium.otf",
      demi_bold_italic:
        "https://media.begenuin.com/webapp_assets/fonts/walmart/EverydaySansMediumItalic.otf",
      heavy:
        "https://media.begenuin.com/webapp_assets/fonts/walmart/EverydaySansBlack.otf",
      heavy_italic:
        "https://media.begenuin.com/webapp_assets/fonts/walmart/EverydaySansBlackItalic.otf",
      medium:
        "https://media.begenuin.com/webapp_assets/fonts/walmart/EverydaySansRegular.otf",
      regular:
        "https://media.begenuin.com/webapp_assets/fonts/walmart/EverydaySansLight.otf",
    },
  },
  camera_enabled: true,
  card_layout_id: 0,
  video_layout_id: 0,
  default_embeds: [
    {
      embed_layout: "default",
      _id: "68109f6e49520a8d125479a9",
      name: "Home/Search Embed",
      style: "carousel",
      type: "brand_feed",
      brand_id: 1441,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        cta_button: {
          text: "Explore More",
          url: "https://google.com",
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        links: {
          is_show_links: true,
          position: "outside",
        },
        show_navigation: false,
        carousel_style: "default",
        autoplay: true,
        feed_display_pref: "default",
        heading: "Specials",
        sub_heading: "Discover what's popular in your community",
        is_carousel_icon: false,
        is_floating_view: false,
        is_expanded_view: false,
        is_show_username: true,
        is_show_view_count: true,
        is_enable_engagement_tools: true,
        show_side_panel: false,
        show_join_community_button: false,
        show_community_share_button: false,
        is_enable_redirection: false,
        is_loop_video: false,
        is_show_social_interaction_data: true,
        community_ids: [],
        is_popup_view: false,
        video_crop: true,
        community_loop_ids: [],
      },
    },
    {
      embed_layout: "default",
      _id: "68109f6e49520a8d125479aa",
      name: "Blog Embed",
      style: "feed",
      type: "brand_feed",
      brand_id: 1441,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        enable_redirection_tools: {
          community: false,
          group: false,
          user: false,
        },
        links: {
          is_show_links: false,
          position: "overlay",
        },
        show_navigation: false,
        carousel_style: "default",
        autoplay: true,
        feed_display_pref: "default",
        heading: "Insider Info",
        sub_heading: "Discover what's popular in your community",
        is_carousel_icon: false,
        is_floating_view: false,
        is_expanded_view: false,
        is_show_username: false,
        is_show_view_count: true,
        is_enable_engagement_tools: true,
        show_side_panel: false,
        show_join_community_button: false,
        show_community_share_button: false,
        is_enable_redirection: false,
        is_loop_video: false,
        is_show_social_interaction_data: false,
        community_ids: [],
        is_popup_view: false,
        video_crop: true,
        community_loop_ids: [],
      },
    },
    {
      embed_layout: "default",
      _id: "68109f6e49520a8d125479ab",
      name: "Home/Search Embed1",
      style: "feed",
      type: "brand_feed",
      brand_id: 1441,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        enable_redirection_tools: {
          community: false,
          group: false,
          user: false,
        },
        links: {
          is_show_links: false,
          position: "overlay",
        },
        show_navigation: false,
        carousel_style: "default",
        autoplay: true,
        feed_display_pref: "default",
        is_carousel_icon: false,
        is_floating_view: false,
        is_expanded_view: false,
        is_show_username: false,
        is_show_view_count: true,
        is_enable_engagement_tools: true,
        show_side_panel: false,
        show_join_community_button: false,
        show_community_share_button: false,
        is_enable_redirection: false,
        is_loop_video: false,
        is_show_social_interaction_data: false,
        community_ids: [],
        is_popup_view: false,
        video_crop: true,
        community_loop_ids: [],
      },
    },
    {
      embed_layout: "default",
      _id: "68109f6e49520a8d125479ac",
      name: "Post-Sales Embed",
      style: "carousel",
      type: "brand_feed",
      brand_id: 1441,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        links: {
          is_show_links: true,
          position: "overlay",
        },
        show_navigation: false,
        carousel_style: "default",
        autoplay: false,
        feed_display_pref: "default",
        heading: "Reviews for you",
        sub_heading: "See what others are getting",
        is_carousel_icon: false,
        is_floating_view: false,
        is_expanded_view: false,
        is_show_username: false,
        is_show_view_count: false,
        is_enable_engagement_tools: true,
        show_side_panel: true,
        show_join_community_button: false,
        show_community_share_button: false,
        is_enable_redirection: false,
        is_loop_video: true,
        is_show_social_interaction_data: false,
        community_ids: [],
        is_popup_view: false,
        video_crop: true,
        community_loop_ids: [],
      },
    },
    {
      embed_layout: "default",
      _id: "68109f6e49520a8d125479ae",
      name: "Home/Blog Embed",
      style: "carousel",
      type: "brand_feed",
      brand_id: 1441,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        links: {
          is_show_links: true,
          position: "overlay",
        },
        show_navigation: false,
        carousel_style: "default",
        autoplay: true,
        feed_display_pref: "default",
        is_carousel_icon: false,
        is_floating_view: true,
        is_expanded_view: false,
        is_show_username: false,
        is_show_view_count: true,
        is_enable_engagement_tools: true,
        show_side_panel: false,
        show_join_community_button: false,
        show_community_share_button: false,
        is_enable_redirection: false,
        is_loop_video: false,
        is_show_social_interaction_data: false,
        community_ids: [],
        is_popup_view: false,
        video_crop: true,
        community_loop_ids: [],
      },
    },
    {
      embed_layout: "default",
      _id: "68109f6e49520a8d125479af",
      name: "Home/Post Sales Embed",
      style: "standard_wall",
      type: "brand_feed",
      brand_id: 1441,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        links: {
          is_show_links: true,
          position: "overlay",
        },
        show_navigation: true,
        carousel_style: "default",
        autoplay: false,
        feed_display_pref: "default",
        is_carousel_icon: false,
        is_floating_view: false,
        is_expanded_view: false,
        is_show_username: false,
        is_show_view_count: false,
        is_enable_engagement_tools: true,
        show_side_panel: false,
        show_join_community_button: false,
        show_community_share_button: false,
        is_enable_redirection: false,
        is_loop_video: true,
        is_show_social_interaction_data: false,
        community_ids: [],
        is_popup_view: false,
        video_crop: true,
        community_loop_ids: [],
      },
    },
    {
      embed_layout: "default",
      _id: "68109f6e49520a8d125479ad",
      name: "PDP Embed",
      style: "carousel",
      type: "brand_feed",
      brand_id: 1441,
      is_default: true,
      customization: {
        dimensions: {
          width: 1080,
          height: 800,
        },
        enable_engagement_tools: {
          repost: true,
          spark: true,
          comment: true,
          share: true,
        },
        links: {
          is_show_links: true,
          position: "overlay",
        },
        show_navigation: false,
        carousel_style: "default",
        autoplay: true,
        feed_display_pref: "default",
        heading: "Reviews for you",
        sub_heading: "Discover what's popular in your community",
        is_carousel_icon: false,
        is_floating_view: false,
        is_expanded_view: false,
        is_show_username: false,
        is_show_view_count: true,
        is_enable_engagement_tools: true,
        show_side_panel: false,
        show_join_community_button: false,
        show_community_share_button: false,
        is_enable_redirection: false,
        is_loop_video: false,
        is_show_social_interaction_data: false,
        community_ids: [],
        is_popup_view: false,
        video_crop: true,
        community_loop_ids: [],
      },
    },
  ],
  slogan: {
    text: "Save Money. Live Better.",
    image:
      "https://media.begenuin.com/uploads/brands/slogan_image/20369be139801445.png",
    font: {
      _id: "65fd65cf4eb212b22bcb840e",
      style: "normal",
      weight: "normal",
    },
  },
  environment: "PROD",
  cta_config: {
    button_color: "#0071ce",
    text_color: "#FFFFFF",
    button_radius: 20,
  },
};

export const testEmbedData: EmbedDataType = {
  _id: "6899e76291098466d50db763",
  name: "Apple AirPods",
  style: "carousel",
  type: "loop_feed",
  brand_id: 1441,
  customization: {
    dimensions: {
      width:800,
      height: 600,
    },
    cta_button: {
      text: "",
      url: "",
      color: "#023F9A",
      text_color: "#FFFFFF",
    },
    enable_engagement_tools: {
      repost: false,
      spark: true,
      comment: true,
      share: true,
    },
    enable_redirection_tools: {
      community: true,
      group: true,
      user: true,
    },
    links: {
      is_show_links: false,
      position: "overlay",
    },
    carousel_style: "default",
    autoplay: false,
    feed_display_pref: "default",
    heading: "",
    heading_text_color: "#212529",
    sub_heading: "",
    sub_heading_text_color: "#6C757D",
    is_carousel_icon: false,
    is_floating_view: false,
    is_show_username: false,
    is_show_view_count: false,
    is_enable_engagement_tools: true,
    show_side_panel: true,
    show_join_community_button: true,
    show_community_share_button: true,
    is_enable_redirection: true,
    is_loop_video: false,
    is_show_social_interaction_data: false,
    community_ids: [],
    community_loop_ids: [
      {
        loop_id: "33e065a2-3e72-435f-bd36-63dae3d03b73",
        community_id: "68b7eb35-822b-40b6-af2f-0d3d608ecdce",
      },
    ],
    is_popup_view: true,
    video_crop: true,
  },
  embed_layout: "default",
  card_layout_id: 6,
  video_layout_id: 5,
  __v: 0,
  is_live: false,
};
