// TODO: change optional ot non-optional params.
export const PATH_NAME = {
  loop: (id?: string) => `/loop/${id}`,
  video: (id?: string) => `/video/${id}`,
  profile: (id?: string) => `/profile/${id}`,
  community: (id?: string) => `/community/${id}`,
  settings: (page?: string) => `/settings/${page}`,
  brand: (id?: string) => `/brand/${id}`,
  home: () => `/home`,
  popular: () => `/popular`,
  latest: () => `/latest`,
  search: () => `/search`,
  build: () => `/`,
  manage: () => `/manage`,
  market: () => `/market`,
  pricing: () => `/pricing`,
  discover: () => '/discover',
  careers: () => 'https://careers.begenuin.com',
  adreels: () => 'https://creatives.begenuin.com/',
  yahoo: () => 'https://finance.yahoo.com/news/genuin-unveils-social-paradigm-empowering-140027873.html',
  businessinsider: () =>
    'https://markets.businessinsider.com/news/stocks/genuin-is-reinventing-social-connections-with-a-communityfirst-approach-1032839987',
  terms: `${process.env.NEXT_PUBLIC_HOST_URL}/terms`,
  privacy: `${process.env.NEXT_PUBLIC_HOST_URL}/privacy`,
}
